// Code generated by ent, DO NOT EDIT.

package compendiumclass

import (
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldDescription, v))
}

// HitDie applies equality check predicate on the "hit_die" field. It's identical to HitDieEQ.
func HitDie(v int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldHitDie, v))
}

// PrimaryAbility applies equality check predicate on the "primary_ability" field. It's identical to PrimaryAbilityEQ.
func PrimaryAbility(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldPrimaryAbility, v))
}

// SavingThrows applies equality check predicate on the "saving_throws" field. It's identical to SavingThrowsEQ.
func SavingThrows(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSavingThrows, v))
}

// Proficiencies applies equality check predicate on the "proficiencies" field. It's identical to ProficienciesEQ.
func Proficiencies(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldProficiencies, v))
}

// SpellcastingAbility applies equality check predicate on the "spellcasting_ability" field. It's identical to SpellcastingAbilityEQ.
func SpellcastingAbility(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSpellcastingAbility, v))
}

// SourcePage applies equality check predicate on the "source_page" field. It's identical to SourcePageEQ.
func SourcePage(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSourcePage, v))
}

// System applies equality check predicate on the "system" field. It's identical to SystemEQ.
func System(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSystem, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSource, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldDescription, v))
}

// HitDieEQ applies the EQ predicate on the "hit_die" field.
func HitDieEQ(v int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldHitDie, v))
}

// HitDieNEQ applies the NEQ predicate on the "hit_die" field.
func HitDieNEQ(v int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldHitDie, v))
}

// HitDieIn applies the In predicate on the "hit_die" field.
func HitDieIn(vs ...int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldHitDie, vs...))
}

// HitDieNotIn applies the NotIn predicate on the "hit_die" field.
func HitDieNotIn(vs ...int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldHitDie, vs...))
}

// HitDieGT applies the GT predicate on the "hit_die" field.
func HitDieGT(v int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldHitDie, v))
}

// HitDieGTE applies the GTE predicate on the "hit_die" field.
func HitDieGTE(v int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldHitDie, v))
}

// HitDieLT applies the LT predicate on the "hit_die" field.
func HitDieLT(v int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldHitDie, v))
}

// HitDieLTE applies the LTE predicate on the "hit_die" field.
func HitDieLTE(v int) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldHitDie, v))
}

// PrimaryAbilityEQ applies the EQ predicate on the "primary_ability" field.
func PrimaryAbilityEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldPrimaryAbility, v))
}

// PrimaryAbilityNEQ applies the NEQ predicate on the "primary_ability" field.
func PrimaryAbilityNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldPrimaryAbility, v))
}

// PrimaryAbilityIn applies the In predicate on the "primary_ability" field.
func PrimaryAbilityIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldPrimaryAbility, vs...))
}

// PrimaryAbilityNotIn applies the NotIn predicate on the "primary_ability" field.
func PrimaryAbilityNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldPrimaryAbility, vs...))
}

// PrimaryAbilityGT applies the GT predicate on the "primary_ability" field.
func PrimaryAbilityGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldPrimaryAbility, v))
}

// PrimaryAbilityGTE applies the GTE predicate on the "primary_ability" field.
func PrimaryAbilityGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldPrimaryAbility, v))
}

// PrimaryAbilityLT applies the LT predicate on the "primary_ability" field.
func PrimaryAbilityLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldPrimaryAbility, v))
}

// PrimaryAbilityLTE applies the LTE predicate on the "primary_ability" field.
func PrimaryAbilityLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldPrimaryAbility, v))
}

// PrimaryAbilityContains applies the Contains predicate on the "primary_ability" field.
func PrimaryAbilityContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldPrimaryAbility, v))
}

// PrimaryAbilityHasPrefix applies the HasPrefix predicate on the "primary_ability" field.
func PrimaryAbilityHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldPrimaryAbility, v))
}

// PrimaryAbilityHasSuffix applies the HasSuffix predicate on the "primary_ability" field.
func PrimaryAbilityHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldPrimaryAbility, v))
}

// PrimaryAbilityEqualFold applies the EqualFold predicate on the "primary_ability" field.
func PrimaryAbilityEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldPrimaryAbility, v))
}

// PrimaryAbilityContainsFold applies the ContainsFold predicate on the "primary_ability" field.
func PrimaryAbilityContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldPrimaryAbility, v))
}

// SavingThrowsEQ applies the EQ predicate on the "saving_throws" field.
func SavingThrowsEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSavingThrows, v))
}

// SavingThrowsNEQ applies the NEQ predicate on the "saving_throws" field.
func SavingThrowsNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldSavingThrows, v))
}

// SavingThrowsIn applies the In predicate on the "saving_throws" field.
func SavingThrowsIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldSavingThrows, vs...))
}

// SavingThrowsNotIn applies the NotIn predicate on the "saving_throws" field.
func SavingThrowsNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldSavingThrows, vs...))
}

// SavingThrowsGT applies the GT predicate on the "saving_throws" field.
func SavingThrowsGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldSavingThrows, v))
}

// SavingThrowsGTE applies the GTE predicate on the "saving_throws" field.
func SavingThrowsGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldSavingThrows, v))
}

// SavingThrowsLT applies the LT predicate on the "saving_throws" field.
func SavingThrowsLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldSavingThrows, v))
}

// SavingThrowsLTE applies the LTE predicate on the "saving_throws" field.
func SavingThrowsLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldSavingThrows, v))
}

// SavingThrowsContains applies the Contains predicate on the "saving_throws" field.
func SavingThrowsContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldSavingThrows, v))
}

// SavingThrowsHasPrefix applies the HasPrefix predicate on the "saving_throws" field.
func SavingThrowsHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldSavingThrows, v))
}

// SavingThrowsHasSuffix applies the HasSuffix predicate on the "saving_throws" field.
func SavingThrowsHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldSavingThrows, v))
}

// SavingThrowsEqualFold applies the EqualFold predicate on the "saving_throws" field.
func SavingThrowsEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldSavingThrows, v))
}

// SavingThrowsContainsFold applies the ContainsFold predicate on the "saving_throws" field.
func SavingThrowsContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldSavingThrows, v))
}

// ProficienciesEQ applies the EQ predicate on the "proficiencies" field.
func ProficienciesEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldProficiencies, v))
}

// ProficienciesNEQ applies the NEQ predicate on the "proficiencies" field.
func ProficienciesNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldProficiencies, v))
}

// ProficienciesIn applies the In predicate on the "proficiencies" field.
func ProficienciesIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldProficiencies, vs...))
}

// ProficienciesNotIn applies the NotIn predicate on the "proficiencies" field.
func ProficienciesNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldProficiencies, vs...))
}

// ProficienciesGT applies the GT predicate on the "proficiencies" field.
func ProficienciesGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldProficiencies, v))
}

// ProficienciesGTE applies the GTE predicate on the "proficiencies" field.
func ProficienciesGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldProficiencies, v))
}

// ProficienciesLT applies the LT predicate on the "proficiencies" field.
func ProficienciesLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldProficiencies, v))
}

// ProficienciesLTE applies the LTE predicate on the "proficiencies" field.
func ProficienciesLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldProficiencies, v))
}

// ProficienciesContains applies the Contains predicate on the "proficiencies" field.
func ProficienciesContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldProficiencies, v))
}

// ProficienciesHasPrefix applies the HasPrefix predicate on the "proficiencies" field.
func ProficienciesHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldProficiencies, v))
}

// ProficienciesHasSuffix applies the HasSuffix predicate on the "proficiencies" field.
func ProficienciesHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldProficiencies, v))
}

// ProficienciesEqualFold applies the EqualFold predicate on the "proficiencies" field.
func ProficienciesEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldProficiencies, v))
}

// ProficienciesContainsFold applies the ContainsFold predicate on the "proficiencies" field.
func ProficienciesContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldProficiencies, v))
}

// SpellcastingAbilityEQ applies the EQ predicate on the "spellcasting_ability" field.
func SpellcastingAbilityEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityNEQ applies the NEQ predicate on the "spellcasting_ability" field.
func SpellcastingAbilityNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityIn applies the In predicate on the "spellcasting_ability" field.
func SpellcastingAbilityIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldSpellcastingAbility, vs...))
}

// SpellcastingAbilityNotIn applies the NotIn predicate on the "spellcasting_ability" field.
func SpellcastingAbilityNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldSpellcastingAbility, vs...))
}

// SpellcastingAbilityGT applies the GT predicate on the "spellcasting_ability" field.
func SpellcastingAbilityGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityGTE applies the GTE predicate on the "spellcasting_ability" field.
func SpellcastingAbilityGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityLT applies the LT predicate on the "spellcasting_ability" field.
func SpellcastingAbilityLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityLTE applies the LTE predicate on the "spellcasting_ability" field.
func SpellcastingAbilityLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityContains applies the Contains predicate on the "spellcasting_ability" field.
func SpellcastingAbilityContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityHasPrefix applies the HasPrefix predicate on the "spellcasting_ability" field.
func SpellcastingAbilityHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityHasSuffix applies the HasSuffix predicate on the "spellcasting_ability" field.
func SpellcastingAbilityHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityEqualFold applies the EqualFold predicate on the "spellcasting_ability" field.
func SpellcastingAbilityEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldSpellcastingAbility, v))
}

// SpellcastingAbilityContainsFold applies the ContainsFold predicate on the "spellcasting_ability" field.
func SpellcastingAbilityContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldSpellcastingAbility, v))
}

// SourcePageEQ applies the EQ predicate on the "source_page" field.
func SourcePageEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSourcePage, v))
}

// SourcePageNEQ applies the NEQ predicate on the "source_page" field.
func SourcePageNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldSourcePage, v))
}

// SourcePageIn applies the In predicate on the "source_page" field.
func SourcePageIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldSourcePage, vs...))
}

// SourcePageNotIn applies the NotIn predicate on the "source_page" field.
func SourcePageNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldSourcePage, vs...))
}

// SourcePageGT applies the GT predicate on the "source_page" field.
func SourcePageGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldSourcePage, v))
}

// SourcePageGTE applies the GTE predicate on the "source_page" field.
func SourcePageGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldSourcePage, v))
}

// SourcePageLT applies the LT predicate on the "source_page" field.
func SourcePageLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldSourcePage, v))
}

// SourcePageLTE applies the LTE predicate on the "source_page" field.
func SourcePageLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldSourcePage, v))
}

// SourcePageContains applies the Contains predicate on the "source_page" field.
func SourcePageContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldSourcePage, v))
}

// SourcePageHasPrefix applies the HasPrefix predicate on the "source_page" field.
func SourcePageHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldSourcePage, v))
}

// SourcePageHasSuffix applies the HasSuffix predicate on the "source_page" field.
func SourcePageHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldSourcePage, v))
}

// SourcePageEqualFold applies the EqualFold predicate on the "source_page" field.
func SourcePageEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldSourcePage, v))
}

// SourcePageContainsFold applies the ContainsFold predicate on the "source_page" field.
func SourcePageContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldSourcePage, v))
}

// SystemEQ applies the EQ predicate on the "system" field.
func SystemEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSystem, v))
}

// SystemNEQ applies the NEQ predicate on the "system" field.
func SystemNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldSystem, v))
}

// SystemIn applies the In predicate on the "system" field.
func SystemIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldSystem, vs...))
}

// SystemNotIn applies the NotIn predicate on the "system" field.
func SystemNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldSystem, vs...))
}

// SystemGT applies the GT predicate on the "system" field.
func SystemGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldSystem, v))
}

// SystemGTE applies the GTE predicate on the "system" field.
func SystemGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldSystem, v))
}

// SystemLT applies the LT predicate on the "system" field.
func SystemLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldSystem, v))
}

// SystemLTE applies the LTE predicate on the "system" field.
func SystemLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldSystem, v))
}

// SystemContains applies the Contains predicate on the "system" field.
func SystemContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldSystem, v))
}

// SystemHasPrefix applies the HasPrefix predicate on the "system" field.
func SystemHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldSystem, v))
}

// SystemHasSuffix applies the HasSuffix predicate on the "system" field.
func SystemHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldSystem, v))
}

// SystemEqualFold applies the EqualFold predicate on the "system" field.
func SystemEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldSystem, v))
}

// SystemContainsFold applies the ContainsFold predicate on the "system" field.
func SystemContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldSystem, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.FieldContainsFold(FieldSource, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CompendiumClass) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CompendiumClass) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CompendiumClass) predicate.CompendiumClass {
	return predicate.CompendiumClass(sql.NotPredicates(p))
}
