import type { ViewState } from '../types';

export {};

declare global {
  interface Window {
    showView: (view: ViewState) => void;
    toggleTheme: () => void;
    toggleEink: () => void;
    showModal: (title: string, bodyHtml: string) => void;
    hideModal: () => void;
    toast: (msg: string, opts?: unknown, duration?: number) => void;
    bootstrap: unknown;
    setDiceExpr: (expr: string) => void;
    rollWithAdvantage: (isAdv: boolean) => Promise<void>;
    renderDiceTab: () => void;
    doRoll: () => Promise<void>;
    loadDiceHistory: () => Promise<void>;
    toggleDiceSound: () => void;
    showSearchOverlay: () => void;
    hideSearchOverlay: () => void;
    doSearch: (query?: string) => Promise<void>;
    initSearch: () => void;
    openPdfViewer: (url: string, title?: string) => void;
    pdfViewerPrevPage: () => void;
    pdfViewerNextPage: () => void;
    pdfViewerZoomIn: () => void;
    pdfViewerZoomOut: () => void;
    pdfViewerFitToWidth: () => void;
    pdfViewerDownload: () => void;
    openAIGenModal: (mode: string, targetId: string, promptHint?: string, title?: string) => void;
    generateWithAI: () => Promise<void>;
    regenerateWithAI: () => void;
    insertAIGenResult: () => void;
    replaceAIGenResult: () => void;
    htmx: { process: (el: Element) => void; trigger: (el: Element, event: string) => void; ajax: (method: string, path: string, opts: unknown) => void } & Record<string, unknown>;
    showCombatTracker: () => Promise<void>;
    showEncounterBuilder: () => Promise<void>;
    showEncounterDetail: (id: number) => Promise<void>;
    showParty: () => Promise<void>;
    showManageCampaign: (id: number, name: string, partyName?: string) => Promise<void>;
    showFactions: () => void;
    showKnowledge: (campaignId?: number) => void;
    showCopilot: (campaignId?: number) => void;
    refreshCopilotPanel: () => Promise<void>;
    copilotAsk: () => Promise<void>;
    copilotNewConversation: () => void;
    copilotLoadConversation: (id: number | string) => Promise<void>;
    copilotSummarizeTranscript: () => Promise<void>;
    copilotIngestTranscript: () => Promise<void>;
    showCopilotPrep: () => Promise<void>;
    showTimeline: () => void;
    loadCompendiumTab: (tab: string) => void;
    renameParty: (id: number, name: string, desc: string) => void;
    showCampaignDashboard: (id: number, name: string) => void;
    playAmbience: (track: string, volume?: number) => void;
    stopAmbience: () => void;
    showAmbienceControls: (campaignId: number) => void;
    ambiencePlay: (campaignId: number, track: string) => Promise<void>;
    ambienceStop: (campaignId: number) => Promise<void>;
    showBattlemap: (campaignId?: number) => Promise<void>;
    battlemapSync: (campaignId: number) => Promise<void>;
    battlemapAddToken: (campaignId: number) => Promise<void>;
    battlemapSaveToken: (campaignId: number) => Promise<void>;
    battlemapRemoveToken: (tokenId: number) => Promise<void>;
    showCharStatsModal: (id: number) => Promise<void>;
    showCharNotes: (id: number) => void;
    renderStepper: (field: string, value: number, delta: number, min?: number, max?: number, label?: string, size?: string) => string;
    renderStats: () => void;
    renderCombat: () => void;
    renderResources: () => Promise<void> | void;
    renderInventory: () => void;
    renderSheet: () => void;
    renderSpells: () => void;
    updateField: (field: string, value: unknown) => void;
    saveCharacter: () => Promise<void>;
    autoSaveField: (field: string, el: HTMLElement) => void;
    stepperField: (field: string, delta: number, min?: number, max?: number) => void;
    editStepperValue: (field: string, el: HTMLElement) => void;
    coinStepper: (coin: string, delta: number) => Promise<void>;
    updateSaveBtnState: () => void;
    canEditCharacter: boolean;
    renderCrafting: () => void;
    renderDetails: () => void;
    updateXPBar: () => void;
    showTable: () => Promise<void>;
    hideTable: () => void;
    rollFromTable: () => Promise<void>;
    handleLiveRoll: (payload: unknown) => void;
    handleSpellCast: (payload: unknown) => void;
    refreshTableInitiative: () => Promise<void>;
    refreshTableHandouts: () => Promise<void>;
    applyDamage: () => Promise<void>;
    applyHeal: () => Promise<void>;
    showAttackModal: (entryId: number) => Promise<void>;
    previewAttack: () => Promise<void>;
    applyAttack: () => Promise<void>;
    refreshCombatLog: () => Promise<void>;
    showExternalImport: () => void;
    showExternalImportLogs: () => Promise<void> | void;
    previewExternalImport: () => Promise<void>;
    commitExternalImport: () => Promise<void>;
    rollbackExternalImport: (id: number) => Promise<void>;
    extImportKindChanged: () => void;
    // allow any other expose names without error
    [key: string]: unknown;
  }
}
