#!/usr/bin/env bash
set -e
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "==> check-tidy"
"$SCRIPT_DIR/check-tidy.sh"
echo "==> check-fmt"
"$SCRIPT_DIR/check-fmt.sh"
echo "==> check-vet"
"$SCRIPT_DIR/check-vet.sh"
echo "==> check-ts"
"$SCRIPT_DIR/check-ts.sh"
echo "==> check-testid"
"$SCRIPT_DIR/check-testid.sh"
echo "==> test-go"
"$SCRIPT_DIR/test-go.sh"
echo "==> test-vitest"
"$SCRIPT_DIR/test-vitest.sh"
echo "==> build-server"
"$SCRIPT_DIR/build-server.sh"
echo "==> test-e2e"
"$SCRIPT_DIR/test-e2e.sh"
echo "==> test-docker"
"$SCRIPT_DIR/test-docker.sh"
echo "All gates passed."
