// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/aiendpoint"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AIEndpointCreate is the builder for creating a AIEndpoint entity.
type AIEndpointCreate struct {
	config
	mutation *AIEndpointMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *AIEndpointCreate) SetName(v string) *AIEndpointCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *AIEndpointCreate) SetType(v aiendpoint.Type) *AIEndpointCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *AIEndpointCreate) SetBaseURL(v string) *AIEndpointCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetEncryptedAPIKey sets the "encrypted_api_key" field.
func (_c *AIEndpointCreate) SetEncryptedAPIKey(v string) *AIEndpointCreate {
	_c.mutation.SetEncryptedAPIKey(v)
	return _c
}

// SetModel sets the "model" field.
func (_c *AIEndpointCreate) SetModel(v string) *AIEndpointCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *AIEndpointCreate) SetTags(v []string) *AIEndpointCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AIEndpointCreate) SetEnabled(v bool) *AIEndpointCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AIEndpointCreate) SetNillableEnabled(v *bool) *AIEndpointCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetTemperature sets the "temperature" field.
func (_c *AIEndpointCreate) SetTemperature(v float64) *AIEndpointCreate {
	_c.mutation.SetTemperature(v)
	return _c
}

// SetNillableTemperature sets the "temperature" field if the given value is not nil.
func (_c *AIEndpointCreate) SetNillableTemperature(v *float64) *AIEndpointCreate {
	if v != nil {
		_c.SetTemperature(*v)
	}
	return _c
}

// SetMaxTokens sets the "max_tokens" field.
func (_c *AIEndpointCreate) SetMaxTokens(v int) *AIEndpointCreate {
	_c.mutation.SetMaxTokens(v)
	return _c
}

// SetNillableMaxTokens sets the "max_tokens" field if the given value is not nil.
func (_c *AIEndpointCreate) SetNillableMaxTokens(v *int) *AIEndpointCreate {
	if v != nil {
		_c.SetMaxTokens(*v)
	}
	return _c
}

// SetImageSize sets the "image_size" field.
func (_c *AIEndpointCreate) SetImageSize(v string) *AIEndpointCreate {
	_c.mutation.SetImageSize(v)
	return _c
}

// SetNillableImageSize sets the "image_size" field if the given value is not nil.
func (_c *AIEndpointCreate) SetNillableImageSize(v *string) *AIEndpointCreate {
	if v != nil {
		_c.SetImageSize(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AIEndpointCreate) SetCreatedAt(v string) *AIEndpointCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AIEndpointCreate) SetUpdatedAt(v string) *AIEndpointCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AIEndpointCreate) SetID(v int64) *AIEndpointCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the AIEndpointMutation object of the builder.
func (_c *AIEndpointCreate) Mutation() *AIEndpointMutation {
	return _c.mutation
}

// Save creates the AIEndpoint in the database.
func (_c *AIEndpointCreate) Save(ctx context.Context) (*AIEndpoint, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AIEndpointCreate) SaveX(ctx context.Context) *AIEndpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AIEndpointCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AIEndpointCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AIEndpointCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := aiendpoint.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AIEndpointCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AIEndpoint.name"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "AIEndpoint.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := aiendpoint.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "AIEndpoint.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "AIEndpoint.base_url"`)}
	}
	if _, ok := _c.mutation.EncryptedAPIKey(); !ok {
		return &ValidationError{Name: "encrypted_api_key", err: errors.New(`ent: missing required field "AIEndpoint.encrypted_api_key"`)}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "AIEndpoint.model"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "AIEndpoint.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AIEndpoint.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AIEndpoint.updated_at"`)}
	}
	return nil
}

func (_c *AIEndpointCreate) sqlSave(ctx context.Context) (*AIEndpoint, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AIEndpointCreate) createSpec() (*AIEndpoint, *sqlgraph.CreateSpec) {
	var (
		_node = &AIEndpoint{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(aiendpoint.Table, sqlgraph.NewFieldSpec(aiendpoint.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(aiendpoint.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(aiendpoint.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(aiendpoint.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.EncryptedAPIKey(); ok {
		_spec.SetField(aiendpoint.FieldEncryptedAPIKey, field.TypeString, value)
		_node.EncryptedAPIKey = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(aiendpoint.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(aiendpoint.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(aiendpoint.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Temperature(); ok {
		_spec.SetField(aiendpoint.FieldTemperature, field.TypeFloat64, value)
		_node.Temperature = &value
	}
	if value, ok := _c.mutation.MaxTokens(); ok {
		_spec.SetField(aiendpoint.FieldMaxTokens, field.TypeInt, value)
		_node.MaxTokens = &value
	}
	if value, ok := _c.mutation.ImageSize(); ok {
		_spec.SetField(aiendpoint.FieldImageSize, field.TypeString, value)
		_node.ImageSize = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(aiendpoint.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(aiendpoint.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AIEndpoint.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AIEndpointUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AIEndpointCreate) OnConflict(opts ...sql.ConflictOption) *AIEndpointUpsertOne {
	_c.conflict = opts
	return &AIEndpointUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AIEndpoint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AIEndpointCreate) OnConflictColumns(columns ...string) *AIEndpointUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AIEndpointUpsertOne{
		create: _c,
	}
}

type (
	// AIEndpointUpsertOne is the builder for "upsert"-ing
	//  one AIEndpoint node.
	AIEndpointUpsertOne struct {
		create *AIEndpointCreate
	}

	// AIEndpointUpsert is the "OnConflict" setter.
	AIEndpointUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *AIEndpointUpsert) SetName(v string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateName() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *AIEndpointUpsert) SetType(v aiendpoint.Type) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateType() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldType)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *AIEndpointUpsert) SetBaseURL(v string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateBaseURL() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldBaseURL)
	return u
}

// SetEncryptedAPIKey sets the "encrypted_api_key" field.
func (u *AIEndpointUpsert) SetEncryptedAPIKey(v string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldEncryptedAPIKey, v)
	return u
}

// UpdateEncryptedAPIKey sets the "encrypted_api_key" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateEncryptedAPIKey() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldEncryptedAPIKey)
	return u
}

// SetModel sets the "model" field.
func (u *AIEndpointUpsert) SetModel(v string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateModel() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldModel)
	return u
}

// SetTags sets the "tags" field.
func (u *AIEndpointUpsert) SetTags(v []string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldTags, v)
	return u
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateTags() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldTags)
	return u
}

// ClearTags clears the value of the "tags" field.
func (u *AIEndpointUpsert) ClearTags() *AIEndpointUpsert {
	u.SetNull(aiendpoint.FieldTags)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *AIEndpointUpsert) SetEnabled(v bool) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateEnabled() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldEnabled)
	return u
}

// SetTemperature sets the "temperature" field.
func (u *AIEndpointUpsert) SetTemperature(v float64) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldTemperature, v)
	return u
}

// UpdateTemperature sets the "temperature" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateTemperature() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldTemperature)
	return u
}

// AddTemperature adds v to the "temperature" field.
func (u *AIEndpointUpsert) AddTemperature(v float64) *AIEndpointUpsert {
	u.Add(aiendpoint.FieldTemperature, v)
	return u
}

// ClearTemperature clears the value of the "temperature" field.
func (u *AIEndpointUpsert) ClearTemperature() *AIEndpointUpsert {
	u.SetNull(aiendpoint.FieldTemperature)
	return u
}

// SetMaxTokens sets the "max_tokens" field.
func (u *AIEndpointUpsert) SetMaxTokens(v int) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldMaxTokens, v)
	return u
}

// UpdateMaxTokens sets the "max_tokens" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateMaxTokens() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldMaxTokens)
	return u
}

// AddMaxTokens adds v to the "max_tokens" field.
func (u *AIEndpointUpsert) AddMaxTokens(v int) *AIEndpointUpsert {
	u.Add(aiendpoint.FieldMaxTokens, v)
	return u
}

// ClearMaxTokens clears the value of the "max_tokens" field.
func (u *AIEndpointUpsert) ClearMaxTokens() *AIEndpointUpsert {
	u.SetNull(aiendpoint.FieldMaxTokens)
	return u
}

// SetImageSize sets the "image_size" field.
func (u *AIEndpointUpsert) SetImageSize(v string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldImageSize, v)
	return u
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateImageSize() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldImageSize)
	return u
}

// ClearImageSize clears the value of the "image_size" field.
func (u *AIEndpointUpsert) ClearImageSize() *AIEndpointUpsert {
	u.SetNull(aiendpoint.FieldImageSize)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *AIEndpointUpsert) SetCreatedAt(v string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateCreatedAt() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AIEndpointUpsert) SetUpdatedAt(v string) *AIEndpointUpsert {
	u.Set(aiendpoint.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AIEndpointUpsert) UpdateUpdatedAt() *AIEndpointUpsert {
	u.SetExcluded(aiendpoint.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AIEndpoint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aiendpoint.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AIEndpointUpsertOne) UpdateNewValues() *AIEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(aiendpoint.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AIEndpoint.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AIEndpointUpsertOne) Ignore() *AIEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AIEndpointUpsertOne) DoNothing() *AIEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AIEndpointCreate.OnConflict
// documentation for more info.
func (u *AIEndpointUpsertOne) Update(set func(*AIEndpointUpsert)) *AIEndpointUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AIEndpointUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AIEndpointUpsertOne) SetName(v string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateName() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *AIEndpointUpsertOne) SetType(v aiendpoint.Type) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateType() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateType()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *AIEndpointUpsertOne) SetBaseURL(v string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateBaseURL() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateBaseURL()
	})
}

// SetEncryptedAPIKey sets the "encrypted_api_key" field.
func (u *AIEndpointUpsertOne) SetEncryptedAPIKey(v string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetEncryptedAPIKey(v)
	})
}

// UpdateEncryptedAPIKey sets the "encrypted_api_key" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateEncryptedAPIKey() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateEncryptedAPIKey()
	})
}

// SetModel sets the "model" field.
func (u *AIEndpointUpsertOne) SetModel(v string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateModel() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateModel()
	})
}

// SetTags sets the "tags" field.
func (u *AIEndpointUpsertOne) SetTags(v []string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateTags() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *AIEndpointUpsertOne) ClearTags() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearTags()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AIEndpointUpsertOne) SetEnabled(v bool) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateEnabled() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateEnabled()
	})
}

// SetTemperature sets the "temperature" field.
func (u *AIEndpointUpsertOne) SetTemperature(v float64) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetTemperature(v)
	})
}

// AddTemperature adds v to the "temperature" field.
func (u *AIEndpointUpsertOne) AddTemperature(v float64) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.AddTemperature(v)
	})
}

// UpdateTemperature sets the "temperature" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateTemperature() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateTemperature()
	})
}

// ClearTemperature clears the value of the "temperature" field.
func (u *AIEndpointUpsertOne) ClearTemperature() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearTemperature()
	})
}

// SetMaxTokens sets the "max_tokens" field.
func (u *AIEndpointUpsertOne) SetMaxTokens(v int) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetMaxTokens(v)
	})
}

// AddMaxTokens adds v to the "max_tokens" field.
func (u *AIEndpointUpsertOne) AddMaxTokens(v int) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.AddMaxTokens(v)
	})
}

// UpdateMaxTokens sets the "max_tokens" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateMaxTokens() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateMaxTokens()
	})
}

// ClearMaxTokens clears the value of the "max_tokens" field.
func (u *AIEndpointUpsertOne) ClearMaxTokens() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearMaxTokens()
	})
}

// SetImageSize sets the "image_size" field.
func (u *AIEndpointUpsertOne) SetImageSize(v string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetImageSize(v)
	})
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateImageSize() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateImageSize()
	})
}

// ClearImageSize clears the value of the "image_size" field.
func (u *AIEndpointUpsertOne) ClearImageSize() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearImageSize()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AIEndpointUpsertOne) SetCreatedAt(v string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateCreatedAt() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AIEndpointUpsertOne) SetUpdatedAt(v string) *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AIEndpointUpsertOne) UpdateUpdatedAt() *AIEndpointUpsertOne {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AIEndpointUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AIEndpointCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AIEndpointUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AIEndpointUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AIEndpointUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AIEndpointCreateBulk is the builder for creating many AIEndpoint entities in bulk.
type AIEndpointCreateBulk struct {
	config
	err      error
	builders []*AIEndpointCreate
	conflict []sql.ConflictOption
}

// Save creates the AIEndpoint entities in the database.
func (_c *AIEndpointCreateBulk) Save(ctx context.Context) ([]*AIEndpoint, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AIEndpoint, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AIEndpointMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AIEndpointCreateBulk) SaveX(ctx context.Context) []*AIEndpoint {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AIEndpointCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AIEndpointCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AIEndpoint.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AIEndpointUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *AIEndpointCreateBulk) OnConflict(opts ...sql.ConflictOption) *AIEndpointUpsertBulk {
	_c.conflict = opts
	return &AIEndpointUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AIEndpoint.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AIEndpointCreateBulk) OnConflictColumns(columns ...string) *AIEndpointUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AIEndpointUpsertBulk{
		create: _c,
	}
}

// AIEndpointUpsertBulk is the builder for "upsert"-ing
// a bulk of AIEndpoint nodes.
type AIEndpointUpsertBulk struct {
	create *AIEndpointCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AIEndpoint.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(aiendpoint.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AIEndpointUpsertBulk) UpdateNewValues() *AIEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(aiendpoint.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AIEndpoint.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AIEndpointUpsertBulk) Ignore() *AIEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AIEndpointUpsertBulk) DoNothing() *AIEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AIEndpointCreateBulk.OnConflict
// documentation for more info.
func (u *AIEndpointUpsertBulk) Update(set func(*AIEndpointUpsert)) *AIEndpointUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AIEndpointUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *AIEndpointUpsertBulk) SetName(v string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateName() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *AIEndpointUpsertBulk) SetType(v aiendpoint.Type) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateType() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateType()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *AIEndpointUpsertBulk) SetBaseURL(v string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateBaseURL() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateBaseURL()
	})
}

// SetEncryptedAPIKey sets the "encrypted_api_key" field.
func (u *AIEndpointUpsertBulk) SetEncryptedAPIKey(v string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetEncryptedAPIKey(v)
	})
}

// UpdateEncryptedAPIKey sets the "encrypted_api_key" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateEncryptedAPIKey() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateEncryptedAPIKey()
	})
}

// SetModel sets the "model" field.
func (u *AIEndpointUpsertBulk) SetModel(v string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateModel() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateModel()
	})
}

// SetTags sets the "tags" field.
func (u *AIEndpointUpsertBulk) SetTags(v []string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetTags(v)
	})
}

// UpdateTags sets the "tags" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateTags() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateTags()
	})
}

// ClearTags clears the value of the "tags" field.
func (u *AIEndpointUpsertBulk) ClearTags() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearTags()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AIEndpointUpsertBulk) SetEnabled(v bool) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateEnabled() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateEnabled()
	})
}

// SetTemperature sets the "temperature" field.
func (u *AIEndpointUpsertBulk) SetTemperature(v float64) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetTemperature(v)
	})
}

// AddTemperature adds v to the "temperature" field.
func (u *AIEndpointUpsertBulk) AddTemperature(v float64) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.AddTemperature(v)
	})
}

// UpdateTemperature sets the "temperature" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateTemperature() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateTemperature()
	})
}

// ClearTemperature clears the value of the "temperature" field.
func (u *AIEndpointUpsertBulk) ClearTemperature() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearTemperature()
	})
}

// SetMaxTokens sets the "max_tokens" field.
func (u *AIEndpointUpsertBulk) SetMaxTokens(v int) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetMaxTokens(v)
	})
}

// AddMaxTokens adds v to the "max_tokens" field.
func (u *AIEndpointUpsertBulk) AddMaxTokens(v int) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.AddMaxTokens(v)
	})
}

// UpdateMaxTokens sets the "max_tokens" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateMaxTokens() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateMaxTokens()
	})
}

// ClearMaxTokens clears the value of the "max_tokens" field.
func (u *AIEndpointUpsertBulk) ClearMaxTokens() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearMaxTokens()
	})
}

// SetImageSize sets the "image_size" field.
func (u *AIEndpointUpsertBulk) SetImageSize(v string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetImageSize(v)
	})
}

// UpdateImageSize sets the "image_size" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateImageSize() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateImageSize()
	})
}

// ClearImageSize clears the value of the "image_size" field.
func (u *AIEndpointUpsertBulk) ClearImageSize() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.ClearImageSize()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *AIEndpointUpsertBulk) SetCreatedAt(v string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateCreatedAt() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AIEndpointUpsertBulk) SetUpdatedAt(v string) *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AIEndpointUpsertBulk) UpdateUpdatedAt() *AIEndpointUpsertBulk {
	return u.Update(func(s *AIEndpointUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *AIEndpointUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AIEndpointCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AIEndpointCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AIEndpointUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
