// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/campaign"
	"villum/ent/campaignwikipage"
	"villum/ent/predicate"
	"villum/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CampaignWikiPageUpdate is the builder for updating CampaignWikiPage entities.
type CampaignWikiPageUpdate struct {
	config
	hooks    []Hook
	mutation *CampaignWikiPageMutation
}

// Where appends a list predicates to the CampaignWikiPageUpdate builder.
func (_u *CampaignWikiPageUpdate) Where(ps ...predicate.CampaignWikiPage) *CampaignWikiPageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CampaignWikiPageUpdate) SetCampaignID(v int64) *CampaignWikiPageUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableCampaignID(v *int64) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CampaignWikiPageUpdate) SetUserID(v int64) *CampaignWikiPageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableUserID(v *int64) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *CampaignWikiPageUpdate) SetParentID(v int64) *CampaignWikiPageUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableParentID(v *int64) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CampaignWikiPageUpdate) ClearParentID() *CampaignWikiPageUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *CampaignWikiPageUpdate) SetTitle(v string) *CampaignWikiPageUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableTitle(v *string) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *CampaignWikiPageUpdate) SetContent(v string) *CampaignWikiPageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableContent(v *string) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *CampaignWikiPageUpdate) SetVisibility(v string) *CampaignWikiPageUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableVisibility(v *string) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *CampaignWikiPageUpdate) SetTags(v string) *CampaignWikiPageUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableTags(v *string) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CampaignWikiPageUpdate) SetSortOrder(v int) *CampaignWikiPageUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableSortOrder(v *int) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CampaignWikiPageUpdate) AddSortOrder(v int) *CampaignWikiPageUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CampaignWikiPageUpdate) SetCreatedAt(v string) *CampaignWikiPageUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableCreatedAt(v *string) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CampaignWikiPageUpdate) SetUpdatedAt(v string) *CampaignWikiPageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CampaignWikiPageUpdate) SetNillableUpdatedAt(v *string) *CampaignWikiPageUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CampaignWikiPageUpdate) SetCampaign(v *Campaign) *CampaignWikiPageUpdate {
	return _u.SetCampaignID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CampaignWikiPageUpdate) SetUser(v *User) *CampaignWikiPageUpdate {
	return _u.SetUserID(v.ID)
}

// SetParent sets the "parent" edge to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdate) SetParent(v *CampaignWikiPage) *CampaignWikiPageUpdate {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the CampaignWikiPage entity by IDs.
func (_u *CampaignWikiPageUpdate) AddChildIDs(ids ...int64) *CampaignWikiPageUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdate) AddChildren(v ...*CampaignWikiPage) *CampaignWikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the CampaignWikiPageMutation object of the builder.
func (_u *CampaignWikiPageUpdate) Mutation() *CampaignWikiPageMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CampaignWikiPageUpdate) ClearCampaign() *CampaignWikiPageUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CampaignWikiPageUpdate) ClearUser() *CampaignWikiPageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearParent clears the "parent" edge to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdate) ClearParent() *CampaignWikiPageUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdate) ClearChildren() *CampaignWikiPageUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to CampaignWikiPage entities by IDs.
func (_u *CampaignWikiPageUpdate) RemoveChildIDs(ids ...int64) *CampaignWikiPageUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to CampaignWikiPage entities.
func (_u *CampaignWikiPageUpdate) RemoveChildren(v ...*CampaignWikiPage) *CampaignWikiPageUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CampaignWikiPageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignWikiPageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CampaignWikiPageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignWikiPageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CampaignWikiPageUpdate) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignWikiPage.campaign"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignWikiPage.user"`)
	}
	return nil
}

func (_u *CampaignWikiPageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(campaignwikipage.Table, campaignwikipage.Columns, sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(campaignwikipage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(campaignwikipage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(campaignwikipage.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(campaignwikipage.FieldTags, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(campaignwikipage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(campaignwikipage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(campaignwikipage.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(campaignwikipage.FieldUpdatedAt, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.CampaignTable,
			Columns: []string{campaignwikipage.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.CampaignTable,
			Columns: []string{campaignwikipage.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.UserTable,
			Columns: []string{campaignwikipage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.UserTable,
			Columns: []string{campaignwikipage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.ParentTable,
			Columns: []string{campaignwikipage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.ParentTable,
			Columns: []string{campaignwikipage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignwikipage.ChildrenTable,
			Columns: []string{campaignwikipage.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignwikipage.ChildrenTable,
			Columns: []string{campaignwikipage.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignwikipage.ChildrenTable,
			Columns: []string{campaignwikipage.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaignwikipage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CampaignWikiPageUpdateOne is the builder for updating a single CampaignWikiPage entity.
type CampaignWikiPageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CampaignWikiPageMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CampaignWikiPageUpdateOne) SetCampaignID(v int64) *CampaignWikiPageUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableCampaignID(v *int64) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CampaignWikiPageUpdateOne) SetUserID(v int64) *CampaignWikiPageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableUserID(v *int64) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *CampaignWikiPageUpdateOne) SetParentID(v int64) *CampaignWikiPageUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableParentID(v *int64) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *CampaignWikiPageUpdateOne) ClearParentID() *CampaignWikiPageUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetTitle sets the "title" field.
func (_u *CampaignWikiPageUpdateOne) SetTitle(v string) *CampaignWikiPageUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableTitle(v *string) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *CampaignWikiPageUpdateOne) SetContent(v string) *CampaignWikiPageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableContent(v *string) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *CampaignWikiPageUpdateOne) SetVisibility(v string) *CampaignWikiPageUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableVisibility(v *string) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *CampaignWikiPageUpdateOne) SetTags(v string) *CampaignWikiPageUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableTags(v *string) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *CampaignWikiPageUpdateOne) SetSortOrder(v int) *CampaignWikiPageUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableSortOrder(v *int) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *CampaignWikiPageUpdateOne) AddSortOrder(v int) *CampaignWikiPageUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CampaignWikiPageUpdateOne) SetCreatedAt(v string) *CampaignWikiPageUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableCreatedAt(v *string) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CampaignWikiPageUpdateOne) SetUpdatedAt(v string) *CampaignWikiPageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CampaignWikiPageUpdateOne) SetNillableUpdatedAt(v *string) *CampaignWikiPageUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CampaignWikiPageUpdateOne) SetCampaign(v *Campaign) *CampaignWikiPageUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CampaignWikiPageUpdateOne) SetUser(v *User) *CampaignWikiPageUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetParent sets the "parent" edge to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdateOne) SetParent(v *CampaignWikiPage) *CampaignWikiPageUpdateOne {
	return _u.SetParentID(v.ID)
}

// AddChildIDs adds the "children" edge to the CampaignWikiPage entity by IDs.
func (_u *CampaignWikiPageUpdateOne) AddChildIDs(ids ...int64) *CampaignWikiPageUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdateOne) AddChildren(v ...*CampaignWikiPage) *CampaignWikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// Mutation returns the CampaignWikiPageMutation object of the builder.
func (_u *CampaignWikiPageUpdateOne) Mutation() *CampaignWikiPageMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CampaignWikiPageUpdateOne) ClearCampaign() *CampaignWikiPageUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CampaignWikiPageUpdateOne) ClearUser() *CampaignWikiPageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearParent clears the "parent" edge to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdateOne) ClearParent() *CampaignWikiPageUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearChildren clears all "children" edges to the CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdateOne) ClearChildren() *CampaignWikiPageUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to CampaignWikiPage entities by IDs.
func (_u *CampaignWikiPageUpdateOne) RemoveChildIDs(ids ...int64) *CampaignWikiPageUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to CampaignWikiPage entities.
func (_u *CampaignWikiPageUpdateOne) RemoveChildren(v ...*CampaignWikiPage) *CampaignWikiPageUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// Where appends a list predicates to the CampaignWikiPageUpdate builder.
func (_u *CampaignWikiPageUpdateOne) Where(ps ...predicate.CampaignWikiPage) *CampaignWikiPageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CampaignWikiPageUpdateOne) Select(field string, fields ...string) *CampaignWikiPageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CampaignWikiPage entity.
func (_u *CampaignWikiPageUpdateOne) Save(ctx context.Context) (*CampaignWikiPage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignWikiPageUpdateOne) SaveX(ctx context.Context) *CampaignWikiPage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CampaignWikiPageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignWikiPageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CampaignWikiPageUpdateOne) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignWikiPage.campaign"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignWikiPage.user"`)
	}
	return nil
}

func (_u *CampaignWikiPageUpdateOne) sqlSave(ctx context.Context) (_node *CampaignWikiPage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(campaignwikipage.Table, campaignwikipage.Columns, sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CampaignWikiPage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, campaignwikipage.FieldID)
		for _, f := range fields {
			if !campaignwikipage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != campaignwikipage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(campaignwikipage.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(campaignwikipage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(campaignwikipage.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(campaignwikipage.FieldTags, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(campaignwikipage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(campaignwikipage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(campaignwikipage.FieldCreatedAt, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(campaignwikipage.FieldUpdatedAt, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.CampaignTable,
			Columns: []string{campaignwikipage.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.CampaignTable,
			Columns: []string{campaignwikipage.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.UserTable,
			Columns: []string{campaignwikipage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.UserTable,
			Columns: []string{campaignwikipage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.ParentTable,
			Columns: []string{campaignwikipage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignwikipage.ParentTable,
			Columns: []string{campaignwikipage.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignwikipage.ChildrenTable,
			Columns: []string{campaignwikipage.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignwikipage.ChildrenTable,
			Columns: []string{campaignwikipage.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignwikipage.ChildrenTable,
			Columns: []string{campaignwikipage.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignwikipage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CampaignWikiPage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaignwikipage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
