// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/campaign"
	"villum/ent/campaignmap"
	"villum/ent/campaignmappin"
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CampaignMapUpdate is the builder for updating CampaignMap entities.
type CampaignMapUpdate struct {
	config
	hooks    []Hook
	mutation *CampaignMapMutation
}

// Where appends a list predicates to the CampaignMapUpdate builder.
func (_u *CampaignMapUpdate) Where(ps ...predicate.CampaignMap) *CampaignMapUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CampaignMapUpdate) SetCampaignID(v int64) *CampaignMapUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableCampaignID(v *int64) *CampaignMapUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CampaignMapUpdate) SetName(v string) *CampaignMapUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableName(v *string) *CampaignMapUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *CampaignMapUpdate) SetImageURL(v string) *CampaignMapUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableImageURL(v *string) *CampaignMapUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *CampaignMapUpdate) SetWidth(v int) *CampaignMapUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableWidth(v *int) *CampaignMapUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *CampaignMapUpdate) AddWidth(v int) *CampaignMapUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *CampaignMapUpdate) SetHeight(v int) *CampaignMapUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableHeight(v *int) *CampaignMapUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *CampaignMapUpdate) AddHeight(v int) *CampaignMapUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetGridSize sets the "grid_size" field.
func (_u *CampaignMapUpdate) SetGridSize(v int) *CampaignMapUpdate {
	_u.mutation.ResetGridSize()
	_u.mutation.SetGridSize(v)
	return _u
}

// SetNillableGridSize sets the "grid_size" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableGridSize(v *int) *CampaignMapUpdate {
	if v != nil {
		_u.SetGridSize(*v)
	}
	return _u
}

// AddGridSize adds value to the "grid_size" field.
func (_u *CampaignMapUpdate) AddGridSize(v int) *CampaignMapUpdate {
	_u.mutation.AddGridSize(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CampaignMapUpdate) SetIsActive(v bool) *CampaignMapUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableIsActive(v *bool) *CampaignMapUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetFogOfWar sets the "fog_of_war" field.
func (_u *CampaignMapUpdate) SetFogOfWar(v string) *CampaignMapUpdate {
	_u.mutation.SetFogOfWar(v)
	return _u
}

// SetNillableFogOfWar sets the "fog_of_war" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableFogOfWar(v *string) *CampaignMapUpdate {
	if v != nil {
		_u.SetFogOfWar(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CampaignMapUpdate) SetCreatedAt(v string) *CampaignMapUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CampaignMapUpdate) SetNillableCreatedAt(v *string) *CampaignMapUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CampaignMapUpdate) SetCampaign(v *Campaign) *CampaignMapUpdate {
	return _u.SetCampaignID(v.ID)
}

// AddPinIDs adds the "pins" edge to the CampaignMapPin entity by IDs.
func (_u *CampaignMapUpdate) AddPinIDs(ids ...int64) *CampaignMapUpdate {
	_u.mutation.AddPinIDs(ids...)
	return _u
}

// AddPins adds the "pins" edges to the CampaignMapPin entity.
func (_u *CampaignMapUpdate) AddPins(v ...*CampaignMapPin) *CampaignMapUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPinIDs(ids...)
}

// Mutation returns the CampaignMapMutation object of the builder.
func (_u *CampaignMapUpdate) Mutation() *CampaignMapMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CampaignMapUpdate) ClearCampaign() *CampaignMapUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearPins clears all "pins" edges to the CampaignMapPin entity.
func (_u *CampaignMapUpdate) ClearPins() *CampaignMapUpdate {
	_u.mutation.ClearPins()
	return _u
}

// RemovePinIDs removes the "pins" edge to CampaignMapPin entities by IDs.
func (_u *CampaignMapUpdate) RemovePinIDs(ids ...int64) *CampaignMapUpdate {
	_u.mutation.RemovePinIDs(ids...)
	return _u
}

// RemovePins removes "pins" edges to CampaignMapPin entities.
func (_u *CampaignMapUpdate) RemovePins(v ...*CampaignMapPin) *CampaignMapUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePinIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CampaignMapUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignMapUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CampaignMapUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignMapUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CampaignMapUpdate) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignMap.campaign"`)
	}
	return nil
}

func (_u *CampaignMapUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(campaignmap.Table, campaignmap.Columns, sqlgraph.NewFieldSpec(campaignmap.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(campaignmap.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(campaignmap.FieldImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(campaignmap.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(campaignmap.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(campaignmap.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(campaignmap.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GridSize(); ok {
		_spec.SetField(campaignmap.FieldGridSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridSize(); ok {
		_spec.AddField(campaignmap.FieldGridSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(campaignmap.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FogOfWar(); ok {
		_spec.SetField(campaignmap.FieldFogOfWar, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(campaignmap.FieldCreatedAt, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignmap.CampaignTable,
			Columns: []string{campaignmap.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignmap.CampaignTable,
			Columns: []string{campaignmap.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignmap.PinsTable,
			Columns: []string{campaignmap.PinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignmappin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPinsIDs(); len(nodes) > 0 && !_u.mutation.PinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignmap.PinsTable,
			Columns: []string{campaignmap.PinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignmappin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignmap.PinsTable,
			Columns: []string{campaignmap.PinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignmappin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaignmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CampaignMapUpdateOne is the builder for updating a single CampaignMap entity.
type CampaignMapUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CampaignMapMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CampaignMapUpdateOne) SetCampaignID(v int64) *CampaignMapUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableCampaignID(v *int64) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *CampaignMapUpdateOne) SetName(v string) *CampaignMapUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableName(v *string) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *CampaignMapUpdateOne) SetImageURL(v string) *CampaignMapUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableImageURL(v *string) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *CampaignMapUpdateOne) SetWidth(v int) *CampaignMapUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableWidth(v *int) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *CampaignMapUpdateOne) AddWidth(v int) *CampaignMapUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *CampaignMapUpdateOne) SetHeight(v int) *CampaignMapUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableHeight(v *int) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *CampaignMapUpdateOne) AddHeight(v int) *CampaignMapUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetGridSize sets the "grid_size" field.
func (_u *CampaignMapUpdateOne) SetGridSize(v int) *CampaignMapUpdateOne {
	_u.mutation.ResetGridSize()
	_u.mutation.SetGridSize(v)
	return _u
}

// SetNillableGridSize sets the "grid_size" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableGridSize(v *int) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetGridSize(*v)
	}
	return _u
}

// AddGridSize adds value to the "grid_size" field.
func (_u *CampaignMapUpdateOne) AddGridSize(v int) *CampaignMapUpdateOne {
	_u.mutation.AddGridSize(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *CampaignMapUpdateOne) SetIsActive(v bool) *CampaignMapUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableIsActive(v *bool) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetFogOfWar sets the "fog_of_war" field.
func (_u *CampaignMapUpdateOne) SetFogOfWar(v string) *CampaignMapUpdateOne {
	_u.mutation.SetFogOfWar(v)
	return _u
}

// SetNillableFogOfWar sets the "fog_of_war" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableFogOfWar(v *string) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetFogOfWar(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CampaignMapUpdateOne) SetCreatedAt(v string) *CampaignMapUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CampaignMapUpdateOne) SetNillableCreatedAt(v *string) *CampaignMapUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CampaignMapUpdateOne) SetCampaign(v *Campaign) *CampaignMapUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// AddPinIDs adds the "pins" edge to the CampaignMapPin entity by IDs.
func (_u *CampaignMapUpdateOne) AddPinIDs(ids ...int64) *CampaignMapUpdateOne {
	_u.mutation.AddPinIDs(ids...)
	return _u
}

// AddPins adds the "pins" edges to the CampaignMapPin entity.
func (_u *CampaignMapUpdateOne) AddPins(v ...*CampaignMapPin) *CampaignMapUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPinIDs(ids...)
}

// Mutation returns the CampaignMapMutation object of the builder.
func (_u *CampaignMapUpdateOne) Mutation() *CampaignMapMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CampaignMapUpdateOne) ClearCampaign() *CampaignMapUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearPins clears all "pins" edges to the CampaignMapPin entity.
func (_u *CampaignMapUpdateOne) ClearPins() *CampaignMapUpdateOne {
	_u.mutation.ClearPins()
	return _u
}

// RemovePinIDs removes the "pins" edge to CampaignMapPin entities by IDs.
func (_u *CampaignMapUpdateOne) RemovePinIDs(ids ...int64) *CampaignMapUpdateOne {
	_u.mutation.RemovePinIDs(ids...)
	return _u
}

// RemovePins removes "pins" edges to CampaignMapPin entities.
func (_u *CampaignMapUpdateOne) RemovePins(v ...*CampaignMapPin) *CampaignMapUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePinIDs(ids...)
}

// Where appends a list predicates to the CampaignMapUpdate builder.
func (_u *CampaignMapUpdateOne) Where(ps ...predicate.CampaignMap) *CampaignMapUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CampaignMapUpdateOne) Select(field string, fields ...string) *CampaignMapUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CampaignMap entity.
func (_u *CampaignMapUpdateOne) Save(ctx context.Context) (*CampaignMap, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignMapUpdateOne) SaveX(ctx context.Context) *CampaignMap {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CampaignMapUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignMapUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CampaignMapUpdateOne) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignMap.campaign"`)
	}
	return nil
}

func (_u *CampaignMapUpdateOne) sqlSave(ctx context.Context) (_node *CampaignMap, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(campaignmap.Table, campaignmap.Columns, sqlgraph.NewFieldSpec(campaignmap.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CampaignMap.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, campaignmap.FieldID)
		for _, f := range fields {
			if !campaignmap.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != campaignmap.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(campaignmap.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(campaignmap.FieldImageURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(campaignmap.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(campaignmap.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(campaignmap.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(campaignmap.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.GridSize(); ok {
		_spec.SetField(campaignmap.FieldGridSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGridSize(); ok {
		_spec.AddField(campaignmap.FieldGridSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(campaignmap.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FogOfWar(); ok {
		_spec.SetField(campaignmap.FieldFogOfWar, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(campaignmap.FieldCreatedAt, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignmap.CampaignTable,
			Columns: []string{campaignmap.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignmap.CampaignTable,
			Columns: []string{campaignmap.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignmap.PinsTable,
			Columns: []string{campaignmap.PinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignmappin.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPinsIDs(); len(nodes) > 0 && !_u.mutation.PinsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignmap.PinsTable,
			Columns: []string{campaignmap.PinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignmappin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignmap.PinsTable,
			Columns: []string{campaignmap.PinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignmappin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CampaignMap{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaignmap.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
