// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/campaign"
	"villum/ent/campaignmap"
	"villum/ent/campaignmappin"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CampaignMapCreate is the builder for creating a CampaignMap entity.
type CampaignMapCreate struct {
	config
	mutation *CampaignMapMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCampaignID sets the "campaign_id" field.
func (_c *CampaignMapCreate) SetCampaignID(v int64) *CampaignMapCreate {
	_c.mutation.SetCampaignID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *CampaignMapCreate) SetName(v string) *CampaignMapCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *CampaignMapCreate) SetImageURL(v string) *CampaignMapCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *CampaignMapCreate) SetNillableImageURL(v *string) *CampaignMapCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetWidth sets the "width" field.
func (_c *CampaignMapCreate) SetWidth(v int) *CampaignMapCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_c *CampaignMapCreate) SetNillableWidth(v *int) *CampaignMapCreate {
	if v != nil {
		_c.SetWidth(*v)
	}
	return _c
}

// SetHeight sets the "height" field.
func (_c *CampaignMapCreate) SetHeight(v int) *CampaignMapCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_c *CampaignMapCreate) SetNillableHeight(v *int) *CampaignMapCreate {
	if v != nil {
		_c.SetHeight(*v)
	}
	return _c
}

// SetGridSize sets the "grid_size" field.
func (_c *CampaignMapCreate) SetGridSize(v int) *CampaignMapCreate {
	_c.mutation.SetGridSize(v)
	return _c
}

// SetNillableGridSize sets the "grid_size" field if the given value is not nil.
func (_c *CampaignMapCreate) SetNillableGridSize(v *int) *CampaignMapCreate {
	if v != nil {
		_c.SetGridSize(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *CampaignMapCreate) SetIsActive(v bool) *CampaignMapCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *CampaignMapCreate) SetNillableIsActive(v *bool) *CampaignMapCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetFogOfWar sets the "fog_of_war" field.
func (_c *CampaignMapCreate) SetFogOfWar(v string) *CampaignMapCreate {
	_c.mutation.SetFogOfWar(v)
	return _c
}

// SetNillableFogOfWar sets the "fog_of_war" field if the given value is not nil.
func (_c *CampaignMapCreate) SetNillableFogOfWar(v *string) *CampaignMapCreate {
	if v != nil {
		_c.SetFogOfWar(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CampaignMapCreate) SetCreatedAt(v string) *CampaignMapCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CampaignMapCreate) SetNillableCreatedAt(v *string) *CampaignMapCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CampaignMapCreate) SetID(v int64) *CampaignMapCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_c *CampaignMapCreate) SetCampaign(v *Campaign) *CampaignMapCreate {
	return _c.SetCampaignID(v.ID)
}

// AddPinIDs adds the "pins" edge to the CampaignMapPin entity by IDs.
func (_c *CampaignMapCreate) AddPinIDs(ids ...int64) *CampaignMapCreate {
	_c.mutation.AddPinIDs(ids...)
	return _c
}

// AddPins adds the "pins" edges to the CampaignMapPin entity.
func (_c *CampaignMapCreate) AddPins(v ...*CampaignMapPin) *CampaignMapCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPinIDs(ids...)
}

// Mutation returns the CampaignMapMutation object of the builder.
func (_c *CampaignMapCreate) Mutation() *CampaignMapMutation {
	return _c.mutation
}

// Save creates the CampaignMap in the database.
func (_c *CampaignMapCreate) Save(ctx context.Context) (*CampaignMap, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CampaignMapCreate) SaveX(ctx context.Context) *CampaignMap {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CampaignMapCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CampaignMapCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CampaignMapCreate) defaults() {
	if _, ok := _c.mutation.ImageURL(); !ok {
		v := campaignmap.DefaultImageURL
		_c.mutation.SetImageURL(v)
	}
	if _, ok := _c.mutation.Width(); !ok {
		v := campaignmap.DefaultWidth
		_c.mutation.SetWidth(v)
	}
	if _, ok := _c.mutation.Height(); !ok {
		v := campaignmap.DefaultHeight
		_c.mutation.SetHeight(v)
	}
	if _, ok := _c.mutation.GridSize(); !ok {
		v := campaignmap.DefaultGridSize
		_c.mutation.SetGridSize(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := campaignmap.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.FogOfWar(); !ok {
		v := campaignmap.DefaultFogOfWar
		_c.mutation.SetFogOfWar(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := campaignmap.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CampaignMapCreate) check() error {
	if _, ok := _c.mutation.CampaignID(); !ok {
		return &ValidationError{Name: "campaign_id", err: errors.New(`ent: missing required field "CampaignMap.campaign_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CampaignMap.name"`)}
	}
	if _, ok := _c.mutation.ImageURL(); !ok {
		return &ValidationError{Name: "image_url", err: errors.New(`ent: missing required field "CampaignMap.image_url"`)}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "CampaignMap.width"`)}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "CampaignMap.height"`)}
	}
	if _, ok := _c.mutation.GridSize(); !ok {
		return &ValidationError{Name: "grid_size", err: errors.New(`ent: missing required field "CampaignMap.grid_size"`)}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "CampaignMap.is_active"`)}
	}
	if _, ok := _c.mutation.FogOfWar(); !ok {
		return &ValidationError{Name: "fog_of_war", err: errors.New(`ent: missing required field "CampaignMap.fog_of_war"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CampaignMap.created_at"`)}
	}
	if len(_c.mutation.CampaignIDs()) == 0 {
		return &ValidationError{Name: "campaign", err: errors.New(`ent: missing required edge "CampaignMap.campaign"`)}
	}
	return nil
}

func (_c *CampaignMapCreate) sqlSave(ctx context.Context) (*CampaignMap, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CampaignMapCreate) createSpec() (*CampaignMap, *sqlgraph.CreateSpec) {
	var (
		_node = &CampaignMap{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(campaignmap.Table, sqlgraph.NewFieldSpec(campaignmap.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(campaignmap.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(campaignmap.FieldImageURL, field.TypeString, value)
		_node.ImageURL = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(campaignmap.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(campaignmap.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.GridSize(); ok {
		_spec.SetField(campaignmap.FieldGridSize, field.TypeInt, value)
		_node.GridSize = value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(campaignmap.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.FogOfWar(); ok {
		_spec.SetField(campaignmap.FieldFogOfWar, field.TypeString, value)
		_node.FogOfWar = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(campaignmap.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaignmap.CampaignTable,
			Columns: []string{campaignmap.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CampaignID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PinsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   campaignmap.PinsTable,
			Columns: []string{campaignmap.PinsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaignmappin.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CampaignMap.Create().
//		SetCampaignID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CampaignMapUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *CampaignMapCreate) OnConflict(opts ...sql.ConflictOption) *CampaignMapUpsertOne {
	_c.conflict = opts
	return &CampaignMapUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CampaignMap.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CampaignMapCreate) OnConflictColumns(columns ...string) *CampaignMapUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CampaignMapUpsertOne{
		create: _c,
	}
}

type (
	// CampaignMapUpsertOne is the builder for "upsert"-ing
	//  one CampaignMap node.
	CampaignMapUpsertOne struct {
		create *CampaignMapCreate
	}

	// CampaignMapUpsert is the "OnConflict" setter.
	CampaignMapUpsert struct {
		*sql.UpdateSet
	}
)

// SetCampaignID sets the "campaign_id" field.
func (u *CampaignMapUpsert) SetCampaignID(v int64) *CampaignMapUpsert {
	u.Set(campaignmap.FieldCampaignID, v)
	return u
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateCampaignID() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldCampaignID)
	return u
}

// SetName sets the "name" field.
func (u *CampaignMapUpsert) SetName(v string) *CampaignMapUpsert {
	u.Set(campaignmap.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateName() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldName)
	return u
}

// SetImageURL sets the "image_url" field.
func (u *CampaignMapUpsert) SetImageURL(v string) *CampaignMapUpsert {
	u.Set(campaignmap.FieldImageURL, v)
	return u
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateImageURL() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldImageURL)
	return u
}

// SetWidth sets the "width" field.
func (u *CampaignMapUpsert) SetWidth(v int) *CampaignMapUpsert {
	u.Set(campaignmap.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateWidth() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *CampaignMapUpsert) AddWidth(v int) *CampaignMapUpsert {
	u.Add(campaignmap.FieldWidth, v)
	return u
}

// SetHeight sets the "height" field.
func (u *CampaignMapUpsert) SetHeight(v int) *CampaignMapUpsert {
	u.Set(campaignmap.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateHeight() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *CampaignMapUpsert) AddHeight(v int) *CampaignMapUpsert {
	u.Add(campaignmap.FieldHeight, v)
	return u
}

// SetGridSize sets the "grid_size" field.
func (u *CampaignMapUpsert) SetGridSize(v int) *CampaignMapUpsert {
	u.Set(campaignmap.FieldGridSize, v)
	return u
}

// UpdateGridSize sets the "grid_size" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateGridSize() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldGridSize)
	return u
}

// AddGridSize adds v to the "grid_size" field.
func (u *CampaignMapUpsert) AddGridSize(v int) *CampaignMapUpsert {
	u.Add(campaignmap.FieldGridSize, v)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *CampaignMapUpsert) SetIsActive(v bool) *CampaignMapUpsert {
	u.Set(campaignmap.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateIsActive() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldIsActive)
	return u
}

// SetFogOfWar sets the "fog_of_war" field.
func (u *CampaignMapUpsert) SetFogOfWar(v string) *CampaignMapUpsert {
	u.Set(campaignmap.FieldFogOfWar, v)
	return u
}

// UpdateFogOfWar sets the "fog_of_war" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateFogOfWar() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldFogOfWar)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CampaignMapUpsert) SetCreatedAt(v string) *CampaignMapUpsert {
	u.Set(campaignmap.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CampaignMapUpsert) UpdateCreatedAt() *CampaignMapUpsert {
	u.SetExcluded(campaignmap.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CampaignMap.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(campaignmap.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CampaignMapUpsertOne) UpdateNewValues() *CampaignMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(campaignmap.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CampaignMap.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CampaignMapUpsertOne) Ignore() *CampaignMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CampaignMapUpsertOne) DoNothing() *CampaignMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CampaignMapCreate.OnConflict
// documentation for more info.
func (u *CampaignMapUpsertOne) Update(set func(*CampaignMapUpsert)) *CampaignMapUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CampaignMapUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *CampaignMapUpsertOne) SetCampaignID(v int64) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateCampaignID() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateCampaignID()
	})
}

// SetName sets the "name" field.
func (u *CampaignMapUpsertOne) SetName(v string) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateName() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateName()
	})
}

// SetImageURL sets the "image_url" field.
func (u *CampaignMapUpsertOne) SetImageURL(v string) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateImageURL() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateImageURL()
	})
}

// SetWidth sets the "width" field.
func (u *CampaignMapUpsertOne) SetWidth(v int) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *CampaignMapUpsertOne) AddWidth(v int) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateWidth() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *CampaignMapUpsertOne) SetHeight(v int) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *CampaignMapUpsertOne) AddHeight(v int) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateHeight() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateHeight()
	})
}

// SetGridSize sets the "grid_size" field.
func (u *CampaignMapUpsertOne) SetGridSize(v int) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetGridSize(v)
	})
}

// AddGridSize adds v to the "grid_size" field.
func (u *CampaignMapUpsertOne) AddGridSize(v int) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.AddGridSize(v)
	})
}

// UpdateGridSize sets the "grid_size" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateGridSize() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateGridSize()
	})
}

// SetIsActive sets the "is_active" field.
func (u *CampaignMapUpsertOne) SetIsActive(v bool) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateIsActive() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateIsActive()
	})
}

// SetFogOfWar sets the "fog_of_war" field.
func (u *CampaignMapUpsertOne) SetFogOfWar(v string) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetFogOfWar(v)
	})
}

// UpdateFogOfWar sets the "fog_of_war" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateFogOfWar() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateFogOfWar()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CampaignMapUpsertOne) SetCreatedAt(v string) *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CampaignMapUpsertOne) UpdateCreatedAt() *CampaignMapUpsertOne {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CampaignMapUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CampaignMapCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CampaignMapUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CampaignMapUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CampaignMapUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CampaignMapCreateBulk is the builder for creating many CampaignMap entities in bulk.
type CampaignMapCreateBulk struct {
	config
	err      error
	builders []*CampaignMapCreate
	conflict []sql.ConflictOption
}

// Save creates the CampaignMap entities in the database.
func (_c *CampaignMapCreateBulk) Save(ctx context.Context) ([]*CampaignMap, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CampaignMap, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CampaignMapMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CampaignMapCreateBulk) SaveX(ctx context.Context) []*CampaignMap {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CampaignMapCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CampaignMapCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CampaignMap.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CampaignMapUpsert) {
//			SetCampaignID(v+v).
//		}).
//		Exec(ctx)
func (_c *CampaignMapCreateBulk) OnConflict(opts ...sql.ConflictOption) *CampaignMapUpsertBulk {
	_c.conflict = opts
	return &CampaignMapUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CampaignMap.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CampaignMapCreateBulk) OnConflictColumns(columns ...string) *CampaignMapUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CampaignMapUpsertBulk{
		create: _c,
	}
}

// CampaignMapUpsertBulk is the builder for "upsert"-ing
// a bulk of CampaignMap nodes.
type CampaignMapUpsertBulk struct {
	create *CampaignMapCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CampaignMap.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(campaignmap.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CampaignMapUpsertBulk) UpdateNewValues() *CampaignMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(campaignmap.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CampaignMap.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CampaignMapUpsertBulk) Ignore() *CampaignMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CampaignMapUpsertBulk) DoNothing() *CampaignMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CampaignMapCreateBulk.OnConflict
// documentation for more info.
func (u *CampaignMapUpsertBulk) Update(set func(*CampaignMapUpsert)) *CampaignMapUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CampaignMapUpsert{UpdateSet: update})
	}))
	return u
}

// SetCampaignID sets the "campaign_id" field.
func (u *CampaignMapUpsertBulk) SetCampaignID(v int64) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetCampaignID(v)
	})
}

// UpdateCampaignID sets the "campaign_id" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateCampaignID() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateCampaignID()
	})
}

// SetName sets the "name" field.
func (u *CampaignMapUpsertBulk) SetName(v string) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateName() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateName()
	})
}

// SetImageURL sets the "image_url" field.
func (u *CampaignMapUpsertBulk) SetImageURL(v string) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetImageURL(v)
	})
}

// UpdateImageURL sets the "image_url" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateImageURL() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateImageURL()
	})
}

// SetWidth sets the "width" field.
func (u *CampaignMapUpsertBulk) SetWidth(v int) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *CampaignMapUpsertBulk) AddWidth(v int) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateWidth() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *CampaignMapUpsertBulk) SetHeight(v int) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *CampaignMapUpsertBulk) AddHeight(v int) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateHeight() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateHeight()
	})
}

// SetGridSize sets the "grid_size" field.
func (u *CampaignMapUpsertBulk) SetGridSize(v int) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetGridSize(v)
	})
}

// AddGridSize adds v to the "grid_size" field.
func (u *CampaignMapUpsertBulk) AddGridSize(v int) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.AddGridSize(v)
	})
}

// UpdateGridSize sets the "grid_size" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateGridSize() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateGridSize()
	})
}

// SetIsActive sets the "is_active" field.
func (u *CampaignMapUpsertBulk) SetIsActive(v bool) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateIsActive() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateIsActive()
	})
}

// SetFogOfWar sets the "fog_of_war" field.
func (u *CampaignMapUpsertBulk) SetFogOfWar(v string) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetFogOfWar(v)
	})
}

// UpdateFogOfWar sets the "fog_of_war" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateFogOfWar() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateFogOfWar()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CampaignMapUpsertBulk) SetCreatedAt(v string) *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CampaignMapUpsertBulk) UpdateCreatedAt() *CampaignMapUpsertBulk {
	return u.Update(func(s *CampaignMapUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CampaignMapUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CampaignMapCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CampaignMapCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CampaignMapUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
