// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/campaign"
	"villum/ent/campaigncharacter"
	"villum/ent/character"
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CampaignCharacterUpdate is the builder for updating CampaignCharacter entities.
type CampaignCharacterUpdate struct {
	config
	hooks    []Hook
	mutation *CampaignCharacterMutation
}

// Where appends a list predicates to the CampaignCharacterUpdate builder.
func (_u *CampaignCharacterUpdate) Where(ps ...predicate.CampaignCharacter) *CampaignCharacterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CampaignCharacterUpdate) SetCampaignID(v int64) *CampaignCharacterUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CampaignCharacterUpdate) SetNillableCampaignID(v *int64) *CampaignCharacterUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *CampaignCharacterUpdate) SetCharacterID(v int64) *CampaignCharacterUpdate {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CampaignCharacterUpdate) SetNillableCharacterID(v *int64) *CampaignCharacterUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CampaignCharacterUpdate) SetCampaign(v *Campaign) *CampaignCharacterUpdate {
	return _u.SetCampaignID(v.ID)
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *CampaignCharacterUpdate) SetCharacter(v *Character) *CampaignCharacterUpdate {
	return _u.SetCharacterID(v.ID)
}

// Mutation returns the CampaignCharacterMutation object of the builder.
func (_u *CampaignCharacterUpdate) Mutation() *CampaignCharacterMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CampaignCharacterUpdate) ClearCampaign() *CampaignCharacterUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *CampaignCharacterUpdate) ClearCharacter() *CampaignCharacterUpdate {
	_u.mutation.ClearCharacter()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CampaignCharacterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignCharacterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CampaignCharacterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignCharacterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CampaignCharacterUpdate) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignCharacter.campaign"`)
	}
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignCharacter.character"`)
	}
	return nil
}

func (_u *CampaignCharacterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(campaigncharacter.Table, campaigncharacter.Columns, sqlgraph.NewFieldSpec(campaigncharacter.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CampaignTable,
			Columns: []string{campaigncharacter.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CampaignTable,
			Columns: []string{campaigncharacter.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CharacterTable,
			Columns: []string{campaigncharacter.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CharacterTable,
			Columns: []string{campaigncharacter.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaigncharacter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CampaignCharacterUpdateOne is the builder for updating a single CampaignCharacter entity.
type CampaignCharacterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CampaignCharacterMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CampaignCharacterUpdateOne) SetCampaignID(v int64) *CampaignCharacterUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CampaignCharacterUpdateOne) SetNillableCampaignID(v *int64) *CampaignCharacterUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *CampaignCharacterUpdateOne) SetCharacterID(v int64) *CampaignCharacterUpdateOne {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *CampaignCharacterUpdateOne) SetNillableCharacterID(v *int64) *CampaignCharacterUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CampaignCharacterUpdateOne) SetCampaign(v *Campaign) *CampaignCharacterUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *CampaignCharacterUpdateOne) SetCharacter(v *Character) *CampaignCharacterUpdateOne {
	return _u.SetCharacterID(v.ID)
}

// Mutation returns the CampaignCharacterMutation object of the builder.
func (_u *CampaignCharacterUpdateOne) Mutation() *CampaignCharacterMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CampaignCharacterUpdateOne) ClearCampaign() *CampaignCharacterUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *CampaignCharacterUpdateOne) ClearCharacter() *CampaignCharacterUpdateOne {
	_u.mutation.ClearCharacter()
	return _u
}

// Where appends a list predicates to the CampaignCharacterUpdate builder.
func (_u *CampaignCharacterUpdateOne) Where(ps ...predicate.CampaignCharacter) *CampaignCharacterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CampaignCharacterUpdateOne) Select(field string, fields ...string) *CampaignCharacterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CampaignCharacter entity.
func (_u *CampaignCharacterUpdateOne) Save(ctx context.Context) (*CampaignCharacter, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CampaignCharacterUpdateOne) SaveX(ctx context.Context) *CampaignCharacter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CampaignCharacterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CampaignCharacterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CampaignCharacterUpdateOne) check() error {
	if _u.mutation.CampaignCleared() && len(_u.mutation.CampaignIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignCharacter.campaign"`)
	}
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CampaignCharacter.character"`)
	}
	return nil
}

func (_u *CampaignCharacterUpdateOne) sqlSave(ctx context.Context) (_node *CampaignCharacter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(campaigncharacter.Table, campaigncharacter.Columns, sqlgraph.NewFieldSpec(campaigncharacter.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CampaignCharacter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, campaigncharacter.FieldID)
		for _, f := range fields {
			if !campaigncharacter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != campaigncharacter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CampaignTable,
			Columns: []string{campaigncharacter.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CampaignTable,
			Columns: []string{campaigncharacter.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CharacterTable,
			Columns: []string{campaigncharacter.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   campaigncharacter.CharacterTable,
			Columns: []string{campaigncharacter.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CampaignCharacter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{campaigncharacter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
