// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"villum/ent/charactercondition"
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CharacterConditionDelete is the builder for deleting a CharacterCondition entity.
type CharacterConditionDelete struct {
	config
	hooks    []Hook
	mutation *CharacterConditionMutation
}

// Where appends a list predicates to the CharacterConditionDelete builder.
func (_d *CharacterConditionDelete) Where(ps ...predicate.CharacterCondition) *CharacterConditionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CharacterConditionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CharacterConditionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CharacterConditionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(charactercondition.Table, sqlgraph.NewFieldSpec(charactercondition.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CharacterConditionDeleteOne is the builder for deleting a single CharacterCondition entity.
type CharacterConditionDeleteOne struct {
	_d *CharacterConditionDelete
}

// Where appends a list predicates to the CharacterConditionDelete builder.
func (_d *CharacterConditionDeleteOne) Where(ps ...predicate.CharacterCondition) *CharacterConditionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CharacterConditionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{charactercondition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CharacterConditionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
