// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"villum/ent/character"
	"villum/ent/characterresource"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// CharacterResource is the model entity for the CharacterResource schema.
type CharacterResource struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CharacterID holds the value of the "character_id" field.
	CharacterID int64 `json:"character_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Current holds the value of the "current" field.
	Current int `json:"current,omitempty"`
	// Max holds the value of the "max" field.
	Max int `json:"max,omitempty"`
	// ShortRestRecovery holds the value of the "short_rest_recovery" field.
	ShortRestRecovery bool `json:"short_rest_recovery,omitempty"`
	// LongRestRecovery holds the value of the "long_rest_recovery" field.
	LongRestRecovery bool `json:"long_rest_recovery,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CharacterResourceQuery when eager-loading is set.
	Edges        CharacterResourceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CharacterResourceEdges holds the relations/edges for other nodes in the graph.
type CharacterResourceEdges struct {
	// Character holds the value of the character edge.
	Character *Character `json:"character,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CharacterOrErr returns the Character value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CharacterResourceEdges) CharacterOrErr() (*Character, error) {
	if e.Character != nil {
		return e.Character, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: character.Label}
	}
	return nil, &NotLoadedError{edge: "character"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CharacterResource) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case characterresource.FieldShortRestRecovery, characterresource.FieldLongRestRecovery:
			values[i] = new(sql.NullBool)
		case characterresource.FieldID, characterresource.FieldCharacterID, characterresource.FieldCurrent, characterresource.FieldMax, characterresource.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case characterresource.FieldName, characterresource.FieldIcon, characterresource.FieldCreatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CharacterResource fields.
func (_m *CharacterResource) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case characterresource.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case characterresource.FieldCharacterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field character_id", values[i])
			} else if value.Valid {
				_m.CharacterID = value.Int64
			}
		case characterresource.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case characterresource.FieldCurrent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current", values[i])
			} else if value.Valid {
				_m.Current = int(value.Int64)
			}
		case characterresource.FieldMax:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max", values[i])
			} else if value.Valid {
				_m.Max = int(value.Int64)
			}
		case characterresource.FieldShortRestRecovery:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field short_rest_recovery", values[i])
			} else if value.Valid {
				_m.ShortRestRecovery = value.Bool
			}
		case characterresource.FieldLongRestRecovery:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field long_rest_recovery", values[i])
			} else if value.Valid {
				_m.LongRestRecovery = value.Bool
			}
		case characterresource.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				_m.Icon = value.String
			}
		case characterresource.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case characterresource.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CharacterResource.
// This includes values selected through modifiers, order, etc.
func (_m *CharacterResource) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCharacter queries the "character" edge of the CharacterResource entity.
func (_m *CharacterResource) QueryCharacter() *CharacterQuery {
	return NewCharacterResourceClient(_m.config).QueryCharacter(_m)
}

// Update returns a builder for updating this CharacterResource.
// Note that you need to call CharacterResource.Unwrap() before calling this method if this CharacterResource
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CharacterResource) Update() *CharacterResourceUpdateOne {
	return NewCharacterResourceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CharacterResource entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CharacterResource) Unwrap() *CharacterResource {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CharacterResource is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CharacterResource) String() string {
	var builder strings.Builder
	builder.WriteString("CharacterResource(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("character_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CharacterID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("current=")
	builder.WriteString(fmt.Sprintf("%v", _m.Current))
	builder.WriteString(", ")
	builder.WriteString("max=")
	builder.WriteString(fmt.Sprintf("%v", _m.Max))
	builder.WriteString(", ")
	builder.WriteString("short_rest_recovery=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShortRestRecovery))
	builder.WriteString(", ")
	builder.WriteString("long_rest_recovery=")
	builder.WriteString(fmt.Sprintf("%v", _m.LongRestRecovery))
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(_m.Icon)
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// CharacterResources is a parsable slice of CharacterResource.
type CharacterResources []*CharacterResource
