// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/campaign"
	"villum/ent/combatlogentry"
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CombatLogEntryUpdate is the builder for updating CombatLogEntry entities.
type CombatLogEntryUpdate struct {
	config
	hooks    []Hook
	mutation *CombatLogEntryMutation
}

// Where appends a list predicates to the CombatLogEntryUpdate builder.
func (_u *CombatLogEntryUpdate) Where(ps ...predicate.CombatLogEntry) *CombatLogEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CombatLogEntryUpdate) SetCampaignID(v int64) *CombatLogEntryUpdate {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableCampaignID(v *int64) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// ClearCampaignID clears the value of the "campaign_id" field.
func (_u *CombatLogEntryUpdate) ClearCampaignID() *CombatLogEntryUpdate {
	_u.mutation.ClearCampaignID()
	return _u
}

// SetCombatEntryID sets the "combat_entry_id" field.
func (_u *CombatLogEntryUpdate) SetCombatEntryID(v int64) *CombatLogEntryUpdate {
	_u.mutation.ResetCombatEntryID()
	_u.mutation.SetCombatEntryID(v)
	return _u
}

// SetNillableCombatEntryID sets the "combat_entry_id" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableCombatEntryID(v *int64) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetCombatEntryID(*v)
	}
	return _u
}

// AddCombatEntryID adds value to the "combat_entry_id" field.
func (_u *CombatLogEntryUpdate) AddCombatEntryID(v int64) *CombatLogEntryUpdate {
	_u.mutation.AddCombatEntryID(v)
	return _u
}

// ClearCombatEntryID clears the value of the "combat_entry_id" field.
func (_u *CombatLogEntryUpdate) ClearCombatEntryID() *CombatLogEntryUpdate {
	_u.mutation.ClearCombatEntryID()
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *CombatLogEntryUpdate) SetActorName(v string) *CombatLogEntryUpdate {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableActorName(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *CombatLogEntryUpdate) SetAction(v string) *CombatLogEntryUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableAction(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetName sets the "target_name" field.
func (_u *CombatLogEntryUpdate) SetTargetName(v string) *CombatLogEntryUpdate {
	_u.mutation.SetTargetName(v)
	return _u
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableTargetName(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetTargetName(*v)
	}
	return _u
}

// SetDamage sets the "damage" field.
func (_u *CombatLogEntryUpdate) SetDamage(v int) *CombatLogEntryUpdate {
	_u.mutation.ResetDamage()
	_u.mutation.SetDamage(v)
	return _u
}

// SetNillableDamage sets the "damage" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableDamage(v *int) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetDamage(*v)
	}
	return _u
}

// AddDamage adds value to the "damage" field.
func (_u *CombatLogEntryUpdate) AddDamage(v int) *CombatLogEntryUpdate {
	_u.mutation.AddDamage(v)
	return _u
}

// SetDamageType sets the "damage_type" field.
func (_u *CombatLogEntryUpdate) SetDamageType(v string) *CombatLogEntryUpdate {
	_u.mutation.SetDamageType(v)
	return _u
}

// SetNillableDamageType sets the "damage_type" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableDamageType(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetDamageType(*v)
	}
	return _u
}

// SetHealing sets the "healing" field.
func (_u *CombatLogEntryUpdate) SetHealing(v int) *CombatLogEntryUpdate {
	_u.mutation.ResetHealing()
	_u.mutation.SetHealing(v)
	return _u
}

// SetNillableHealing sets the "healing" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableHealing(v *int) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetHealing(*v)
	}
	return _u
}

// AddHealing adds value to the "healing" field.
func (_u *CombatLogEntryUpdate) AddHealing(v int) *CombatLogEntryUpdate {
	_u.mutation.AddHealing(v)
	return _u
}

// SetConditionApplied sets the "condition_applied" field.
func (_u *CombatLogEntryUpdate) SetConditionApplied(v string) *CombatLogEntryUpdate {
	_u.mutation.SetConditionApplied(v)
	return _u
}

// SetNillableConditionApplied sets the "condition_applied" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableConditionApplied(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetConditionApplied(*v)
	}
	return _u
}

// SetRollExpression sets the "roll_expression" field.
func (_u *CombatLogEntryUpdate) SetRollExpression(v string) *CombatLogEntryUpdate {
	_u.mutation.SetRollExpression(v)
	return _u
}

// SetNillableRollExpression sets the "roll_expression" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableRollExpression(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetRollExpression(*v)
	}
	return _u
}

// SetRollTotal sets the "roll_total" field.
func (_u *CombatLogEntryUpdate) SetRollTotal(v int) *CombatLogEntryUpdate {
	_u.mutation.ResetRollTotal()
	_u.mutation.SetRollTotal(v)
	return _u
}

// SetNillableRollTotal sets the "roll_total" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableRollTotal(v *int) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetRollTotal(*v)
	}
	return _u
}

// AddRollTotal adds value to the "roll_total" field.
func (_u *CombatLogEntryUpdate) AddRollTotal(v int) *CombatLogEntryUpdate {
	_u.mutation.AddRollTotal(v)
	return _u
}

// SetIsCritical sets the "is_critical" field.
func (_u *CombatLogEntryUpdate) SetIsCritical(v bool) *CombatLogEntryUpdate {
	_u.mutation.SetIsCritical(v)
	return _u
}

// SetNillableIsCritical sets the "is_critical" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableIsCritical(v *bool) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetIsCritical(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CombatLogEntryUpdate) SetDescription(v string) *CombatLogEntryUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableDescription(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CombatLogEntryUpdate) SetCreatedAt(v string) *CombatLogEntryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CombatLogEntryUpdate) SetNillableCreatedAt(v *string) *CombatLogEntryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CombatLogEntryUpdate) SetCampaign(v *Campaign) *CombatLogEntryUpdate {
	return _u.SetCampaignID(v.ID)
}

// Mutation returns the CombatLogEntryMutation object of the builder.
func (_u *CombatLogEntryUpdate) Mutation() *CombatLogEntryMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CombatLogEntryUpdate) ClearCampaign() *CombatLogEntryUpdate {
	_u.mutation.ClearCampaign()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CombatLogEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CombatLogEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CombatLogEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CombatLogEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CombatLogEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(combatlogentry.Table, combatlogentry.Columns, sqlgraph.NewFieldSpec(combatlogentry.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CombatEntryID(); ok {
		_spec.SetField(combatlogentry.FieldCombatEntryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCombatEntryID(); ok {
		_spec.AddField(combatlogentry.FieldCombatEntryID, field.TypeInt64, value)
	}
	if _u.mutation.CombatEntryIDCleared() {
		_spec.ClearField(combatlogentry.FieldCombatEntryID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(combatlogentry.FieldActorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(combatlogentry.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetName(); ok {
		_spec.SetField(combatlogentry.FieldTargetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Damage(); ok {
		_spec.SetField(combatlogentry.FieldDamage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDamage(); ok {
		_spec.AddField(combatlogentry.FieldDamage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DamageType(); ok {
		_spec.SetField(combatlogentry.FieldDamageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Healing(); ok {
		_spec.SetField(combatlogentry.FieldHealing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealing(); ok {
		_spec.AddField(combatlogentry.FieldHealing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConditionApplied(); ok {
		_spec.SetField(combatlogentry.FieldConditionApplied, field.TypeString, value)
	}
	if value, ok := _u.mutation.RollExpression(); ok {
		_spec.SetField(combatlogentry.FieldRollExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.RollTotal(); ok {
		_spec.SetField(combatlogentry.FieldRollTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRollTotal(); ok {
		_spec.AddField(combatlogentry.FieldRollTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsCritical(); ok {
		_spec.SetField(combatlogentry.FieldIsCritical, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(combatlogentry.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(combatlogentry.FieldCreatedAt, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   combatlogentry.CampaignTable,
			Columns: []string{combatlogentry.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   combatlogentry.CampaignTable,
			Columns: []string{combatlogentry.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{combatlogentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CombatLogEntryUpdateOne is the builder for updating a single CombatLogEntry entity.
type CombatLogEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CombatLogEntryMutation
}

// SetCampaignID sets the "campaign_id" field.
func (_u *CombatLogEntryUpdateOne) SetCampaignID(v int64) *CombatLogEntryUpdateOne {
	_u.mutation.SetCampaignID(v)
	return _u
}

// SetNillableCampaignID sets the "campaign_id" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableCampaignID(v *int64) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetCampaignID(*v)
	}
	return _u
}

// ClearCampaignID clears the value of the "campaign_id" field.
func (_u *CombatLogEntryUpdateOne) ClearCampaignID() *CombatLogEntryUpdateOne {
	_u.mutation.ClearCampaignID()
	return _u
}

// SetCombatEntryID sets the "combat_entry_id" field.
func (_u *CombatLogEntryUpdateOne) SetCombatEntryID(v int64) *CombatLogEntryUpdateOne {
	_u.mutation.ResetCombatEntryID()
	_u.mutation.SetCombatEntryID(v)
	return _u
}

// SetNillableCombatEntryID sets the "combat_entry_id" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableCombatEntryID(v *int64) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetCombatEntryID(*v)
	}
	return _u
}

// AddCombatEntryID adds value to the "combat_entry_id" field.
func (_u *CombatLogEntryUpdateOne) AddCombatEntryID(v int64) *CombatLogEntryUpdateOne {
	_u.mutation.AddCombatEntryID(v)
	return _u
}

// ClearCombatEntryID clears the value of the "combat_entry_id" field.
func (_u *CombatLogEntryUpdateOne) ClearCombatEntryID() *CombatLogEntryUpdateOne {
	_u.mutation.ClearCombatEntryID()
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *CombatLogEntryUpdateOne) SetActorName(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableActorName(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *CombatLogEntryUpdateOne) SetAction(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableAction(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetName sets the "target_name" field.
func (_u *CombatLogEntryUpdateOne) SetTargetName(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetTargetName(v)
	return _u
}

// SetNillableTargetName sets the "target_name" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableTargetName(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetTargetName(*v)
	}
	return _u
}

// SetDamage sets the "damage" field.
func (_u *CombatLogEntryUpdateOne) SetDamage(v int) *CombatLogEntryUpdateOne {
	_u.mutation.ResetDamage()
	_u.mutation.SetDamage(v)
	return _u
}

// SetNillableDamage sets the "damage" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableDamage(v *int) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetDamage(*v)
	}
	return _u
}

// AddDamage adds value to the "damage" field.
func (_u *CombatLogEntryUpdateOne) AddDamage(v int) *CombatLogEntryUpdateOne {
	_u.mutation.AddDamage(v)
	return _u
}

// SetDamageType sets the "damage_type" field.
func (_u *CombatLogEntryUpdateOne) SetDamageType(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetDamageType(v)
	return _u
}

// SetNillableDamageType sets the "damage_type" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableDamageType(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetDamageType(*v)
	}
	return _u
}

// SetHealing sets the "healing" field.
func (_u *CombatLogEntryUpdateOne) SetHealing(v int) *CombatLogEntryUpdateOne {
	_u.mutation.ResetHealing()
	_u.mutation.SetHealing(v)
	return _u
}

// SetNillableHealing sets the "healing" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableHealing(v *int) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetHealing(*v)
	}
	return _u
}

// AddHealing adds value to the "healing" field.
func (_u *CombatLogEntryUpdateOne) AddHealing(v int) *CombatLogEntryUpdateOne {
	_u.mutation.AddHealing(v)
	return _u
}

// SetConditionApplied sets the "condition_applied" field.
func (_u *CombatLogEntryUpdateOne) SetConditionApplied(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetConditionApplied(v)
	return _u
}

// SetNillableConditionApplied sets the "condition_applied" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableConditionApplied(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetConditionApplied(*v)
	}
	return _u
}

// SetRollExpression sets the "roll_expression" field.
func (_u *CombatLogEntryUpdateOne) SetRollExpression(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetRollExpression(v)
	return _u
}

// SetNillableRollExpression sets the "roll_expression" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableRollExpression(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetRollExpression(*v)
	}
	return _u
}

// SetRollTotal sets the "roll_total" field.
func (_u *CombatLogEntryUpdateOne) SetRollTotal(v int) *CombatLogEntryUpdateOne {
	_u.mutation.ResetRollTotal()
	_u.mutation.SetRollTotal(v)
	return _u
}

// SetNillableRollTotal sets the "roll_total" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableRollTotal(v *int) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetRollTotal(*v)
	}
	return _u
}

// AddRollTotal adds value to the "roll_total" field.
func (_u *CombatLogEntryUpdateOne) AddRollTotal(v int) *CombatLogEntryUpdateOne {
	_u.mutation.AddRollTotal(v)
	return _u
}

// SetIsCritical sets the "is_critical" field.
func (_u *CombatLogEntryUpdateOne) SetIsCritical(v bool) *CombatLogEntryUpdateOne {
	_u.mutation.SetIsCritical(v)
	return _u
}

// SetNillableIsCritical sets the "is_critical" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableIsCritical(v *bool) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetIsCritical(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CombatLogEntryUpdateOne) SetDescription(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableDescription(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CombatLogEntryUpdateOne) SetCreatedAt(v string) *CombatLogEntryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CombatLogEntryUpdateOne) SetNillableCreatedAt(v *string) *CombatLogEntryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCampaign sets the "campaign" edge to the Campaign entity.
func (_u *CombatLogEntryUpdateOne) SetCampaign(v *Campaign) *CombatLogEntryUpdateOne {
	return _u.SetCampaignID(v.ID)
}

// Mutation returns the CombatLogEntryMutation object of the builder.
func (_u *CombatLogEntryUpdateOne) Mutation() *CombatLogEntryMutation {
	return _u.mutation
}

// ClearCampaign clears the "campaign" edge to the Campaign entity.
func (_u *CombatLogEntryUpdateOne) ClearCampaign() *CombatLogEntryUpdateOne {
	_u.mutation.ClearCampaign()
	return _u
}

// Where appends a list predicates to the CombatLogEntryUpdate builder.
func (_u *CombatLogEntryUpdateOne) Where(ps ...predicate.CombatLogEntry) *CombatLogEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CombatLogEntryUpdateOne) Select(field string, fields ...string) *CombatLogEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CombatLogEntry entity.
func (_u *CombatLogEntryUpdateOne) Save(ctx context.Context) (*CombatLogEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CombatLogEntryUpdateOne) SaveX(ctx context.Context) *CombatLogEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CombatLogEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CombatLogEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CombatLogEntryUpdateOne) sqlSave(ctx context.Context) (_node *CombatLogEntry, err error) {
	_spec := sqlgraph.NewUpdateSpec(combatlogentry.Table, combatlogentry.Columns, sqlgraph.NewFieldSpec(combatlogentry.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CombatLogEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, combatlogentry.FieldID)
		for _, f := range fields {
			if !combatlogentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != combatlogentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CombatEntryID(); ok {
		_spec.SetField(combatlogentry.FieldCombatEntryID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCombatEntryID(); ok {
		_spec.AddField(combatlogentry.FieldCombatEntryID, field.TypeInt64, value)
	}
	if _u.mutation.CombatEntryIDCleared() {
		_spec.ClearField(combatlogentry.FieldCombatEntryID, field.TypeInt64)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(combatlogentry.FieldActorName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(combatlogentry.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetName(); ok {
		_spec.SetField(combatlogentry.FieldTargetName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Damage(); ok {
		_spec.SetField(combatlogentry.FieldDamage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDamage(); ok {
		_spec.AddField(combatlogentry.FieldDamage, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DamageType(); ok {
		_spec.SetField(combatlogentry.FieldDamageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Healing(); ok {
		_spec.SetField(combatlogentry.FieldHealing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealing(); ok {
		_spec.AddField(combatlogentry.FieldHealing, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConditionApplied(); ok {
		_spec.SetField(combatlogentry.FieldConditionApplied, field.TypeString, value)
	}
	if value, ok := _u.mutation.RollExpression(); ok {
		_spec.SetField(combatlogentry.FieldRollExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.RollTotal(); ok {
		_spec.SetField(combatlogentry.FieldRollTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRollTotal(); ok {
		_spec.AddField(combatlogentry.FieldRollTotal, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsCritical(); ok {
		_spec.SetField(combatlogentry.FieldIsCritical, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(combatlogentry.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(combatlogentry.FieldCreatedAt, field.TypeString, value)
	}
	if _u.mutation.CampaignCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   combatlogentry.CampaignTable,
			Columns: []string{combatlogentry.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CampaignIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   combatlogentry.CampaignTable,
			Columns: []string{combatlogentry.CampaignColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(campaign.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CombatLogEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{combatlogentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
