// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"villum/ent/character"
	"villum/ent/companion"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Companion is the model entity for the Companion schema.
type Companion struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CharacterID holds the value of the "character_id" field.
	CharacterID int64 `json:"character_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Race holds the value of the "race" field.
	Race string `json:"race,omitempty"`
	// HpMax holds the value of the "hp_max" field.
	HpMax int `json:"hp_max,omitempty"`
	// HpCurrent holds the value of the "hp_current" field.
	HpCurrent int `json:"hp_current,omitempty"`
	// Ac holds the value of the "ac" field.
	Ac int `json:"ac,omitempty"`
	// Str holds the value of the "str" field.
	Str int `json:"str,omitempty"`
	// Dex holds the value of the "dex" field.
	Dex int `json:"dex,omitempty"`
	// Con holds the value of the "con" field.
	Con int `json:"con,omitempty"`
	// Int holds the value of the "int" field.
	Int int `json:"int,omitempty"`
	// Wis holds the value of the "wis" field.
	Wis int `json:"wis,omitempty"`
	// Cha holds the value of the "cha" field.
	Cha int `json:"cha,omitempty"`
	// Speed holds the value of the "speed" field.
	Speed int `json:"speed,omitempty"`
	// Abilities holds the value of the "abilities" field.
	Abilities string `json:"abilities,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// PortraitURL holds the value of the "portrait_url" field.
	PortraitURL string `json:"portrait_url,omitempty"`
	// IsAlive holds the value of the "is_alive" field.
	IsAlive bool `json:"is_alive,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CompanionQuery when eager-loading is set.
	Edges        CompanionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CompanionEdges holds the relations/edges for other nodes in the graph.
type CompanionEdges struct {
	// Character holds the value of the character edge.
	Character *Character `json:"character,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CharacterOrErr returns the Character value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CompanionEdges) CharacterOrErr() (*Character, error) {
	if e.Character != nil {
		return e.Character, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: character.Label}
	}
	return nil, &NotLoadedError{edge: "character"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Companion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case companion.FieldIsAlive:
			values[i] = new(sql.NullBool)
		case companion.FieldID, companion.FieldCharacterID, companion.FieldHpMax, companion.FieldHpCurrent, companion.FieldAc, companion.FieldStr, companion.FieldDex, companion.FieldCon, companion.FieldInt, companion.FieldWis, companion.FieldCha, companion.FieldSpeed:
			values[i] = new(sql.NullInt64)
		case companion.FieldName, companion.FieldType, companion.FieldRace, companion.FieldAbilities, companion.FieldNotes, companion.FieldPortraitURL, companion.FieldCreatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Companion fields.
func (_m *Companion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case companion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case companion.FieldCharacterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field character_id", values[i])
			} else if value.Valid {
				_m.CharacterID = value.Int64
			}
		case companion.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case companion.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case companion.FieldRace:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field race", values[i])
			} else if value.Valid {
				_m.Race = value.String
			}
		case companion.FieldHpMax:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hp_max", values[i])
			} else if value.Valid {
				_m.HpMax = int(value.Int64)
			}
		case companion.FieldHpCurrent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hp_current", values[i])
			} else if value.Valid {
				_m.HpCurrent = int(value.Int64)
			}
		case companion.FieldAc:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ac", values[i])
			} else if value.Valid {
				_m.Ac = int(value.Int64)
			}
		case companion.FieldStr:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field str", values[i])
			} else if value.Valid {
				_m.Str = int(value.Int64)
			}
		case companion.FieldDex:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field dex", values[i])
			} else if value.Valid {
				_m.Dex = int(value.Int64)
			}
		case companion.FieldCon:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field con", values[i])
			} else if value.Valid {
				_m.Con = int(value.Int64)
			}
		case companion.FieldInt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field int", values[i])
			} else if value.Valid {
				_m.Int = int(value.Int64)
			}
		case companion.FieldWis:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field wis", values[i])
			} else if value.Valid {
				_m.Wis = int(value.Int64)
			}
		case companion.FieldCha:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cha", values[i])
			} else if value.Valid {
				_m.Cha = int(value.Int64)
			}
		case companion.FieldSpeed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field speed", values[i])
			} else if value.Valid {
				_m.Speed = int(value.Int64)
			}
		case companion.FieldAbilities:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field abilities", values[i])
			} else if value.Valid {
				_m.Abilities = value.String
			}
		case companion.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case companion.FieldPortraitURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field portrait_url", values[i])
			} else if value.Valid {
				_m.PortraitURL = value.String
			}
		case companion.FieldIsAlive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_alive", values[i])
			} else if value.Valid {
				_m.IsAlive = value.Bool
			}
		case companion.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Companion.
// This includes values selected through modifiers, order, etc.
func (_m *Companion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCharacter queries the "character" edge of the Companion entity.
func (_m *Companion) QueryCharacter() *CharacterQuery {
	return NewCompanionClient(_m.config).QueryCharacter(_m)
}

// Update returns a builder for updating this Companion.
// Note that you need to call Companion.Unwrap() before calling this method if this Companion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Companion) Update() *CompanionUpdateOne {
	return NewCompanionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Companion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Companion) Unwrap() *Companion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Companion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Companion) String() string {
	var builder strings.Builder
	builder.WriteString("Companion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("character_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CharacterID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("race=")
	builder.WriteString(_m.Race)
	builder.WriteString(", ")
	builder.WriteString("hp_max=")
	builder.WriteString(fmt.Sprintf("%v", _m.HpMax))
	builder.WriteString(", ")
	builder.WriteString("hp_current=")
	builder.WriteString(fmt.Sprintf("%v", _m.HpCurrent))
	builder.WriteString(", ")
	builder.WriteString("ac=")
	builder.WriteString(fmt.Sprintf("%v", _m.Ac))
	builder.WriteString(", ")
	builder.WriteString("str=")
	builder.WriteString(fmt.Sprintf("%v", _m.Str))
	builder.WriteString(", ")
	builder.WriteString("dex=")
	builder.WriteString(fmt.Sprintf("%v", _m.Dex))
	builder.WriteString(", ")
	builder.WriteString("con=")
	builder.WriteString(fmt.Sprintf("%v", _m.Con))
	builder.WriteString(", ")
	builder.WriteString("int=")
	builder.WriteString(fmt.Sprintf("%v", _m.Int))
	builder.WriteString(", ")
	builder.WriteString("wis=")
	builder.WriteString(fmt.Sprintf("%v", _m.Wis))
	builder.WriteString(", ")
	builder.WriteString("cha=")
	builder.WriteString(fmt.Sprintf("%v", _m.Cha))
	builder.WriteString(", ")
	builder.WriteString("speed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Speed))
	builder.WriteString(", ")
	builder.WriteString("abilities=")
	builder.WriteString(_m.Abilities)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("portrait_url=")
	builder.WriteString(_m.PortraitURL)
	builder.WriteString(", ")
	builder.WriteString("is_alive=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAlive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// Companions is a parsable slice of Companion.
type Companions []*Companion
