// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"villum/ent/compendiumfeat"
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CompendiumFeatDelete is the builder for deleting a CompendiumFeat entity.
type CompendiumFeatDelete struct {
	config
	hooks    []Hook
	mutation *CompendiumFeatMutation
}

// Where appends a list predicates to the CompendiumFeatDelete builder.
func (_d *CompendiumFeatDelete) Where(ps ...predicate.CompendiumFeat) *CompendiumFeatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CompendiumFeatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompendiumFeatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CompendiumFeatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(compendiumfeat.Table, sqlgraph.NewFieldSpec(compendiumfeat.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CompendiumFeatDeleteOne is the builder for deleting a single CompendiumFeat entity.
type CompendiumFeatDeleteOne struct {
	_d *CompendiumFeatDelete
}

// Where appends a list predicates to the CompendiumFeatDelete builder.
func (_d *CompendiumFeatDeleteOne) Where(ps ...predicate.CompendiumFeat) *CompendiumFeatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CompendiumFeatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{compendiumfeat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CompendiumFeatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
