// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/charactercrafting"
	"villum/ent/craftingrecipe"
	"villum/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CraftingRecipeCreate is the builder for creating a CraftingRecipe entity.
type CraftingRecipeCreate struct {
	config
	mutation *CraftingRecipeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *CraftingRecipeCreate) SetUserID(v int64) *CraftingRecipeCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableUserID(v *int64) *CraftingRecipeCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *CraftingRecipeCreate) SetName(v string) *CraftingRecipeCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *CraftingRecipeCreate) SetDescription(v string) *CraftingRecipeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableDescription(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetCategory sets the "category" field.
func (_c *CraftingRecipeCreate) SetCategory(v string) *CraftingRecipeCreate {
	_c.mutation.SetCategory(v)
	return _c
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableCategory(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetCategory(*v)
	}
	return _c
}

// SetDifficultyDc sets the "difficulty_dc" field.
func (_c *CraftingRecipeCreate) SetDifficultyDc(v int) *CraftingRecipeCreate {
	_c.mutation.SetDifficultyDc(v)
	return _c
}

// SetNillableDifficultyDc sets the "difficulty_dc" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableDifficultyDc(v *int) *CraftingRecipeCreate {
	if v != nil {
		_c.SetDifficultyDc(*v)
	}
	return _c
}

// SetCraftingTimeHours sets the "crafting_time_hours" field.
func (_c *CraftingRecipeCreate) SetCraftingTimeHours(v float64) *CraftingRecipeCreate {
	_c.mutation.SetCraftingTimeHours(v)
	return _c
}

// SetNillableCraftingTimeHours sets the "crafting_time_hours" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableCraftingTimeHours(v *float64) *CraftingRecipeCreate {
	if v != nil {
		_c.SetCraftingTimeHours(*v)
	}
	return _c
}

// SetRequiredTools sets the "required_tools" field.
func (_c *CraftingRecipeCreate) SetRequiredTools(v string) *CraftingRecipeCreate {
	_c.mutation.SetRequiredTools(v)
	return _c
}

// SetNillableRequiredTools sets the "required_tools" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableRequiredTools(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetRequiredTools(*v)
	}
	return _c
}

// SetRequiredMaterials sets the "required_materials" field.
func (_c *CraftingRecipeCreate) SetRequiredMaterials(v string) *CraftingRecipeCreate {
	_c.mutation.SetRequiredMaterials(v)
	return _c
}

// SetNillableRequiredMaterials sets the "required_materials" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableRequiredMaterials(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetRequiredMaterials(*v)
	}
	return _c
}

// SetResultItemName sets the "result_item_name" field.
func (_c *CraftingRecipeCreate) SetResultItemName(v string) *CraftingRecipeCreate {
	_c.mutation.SetResultItemName(v)
	return _c
}

// SetResultItemCategory sets the "result_item_category" field.
func (_c *CraftingRecipeCreate) SetResultItemCategory(v string) *CraftingRecipeCreate {
	_c.mutation.SetResultItemCategory(v)
	return _c
}

// SetNillableResultItemCategory sets the "result_item_category" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableResultItemCategory(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetResultItemCategory(*v)
	}
	return _c
}

// SetResultQuantity sets the "result_quantity" field.
func (_c *CraftingRecipeCreate) SetResultQuantity(v int) *CraftingRecipeCreate {
	_c.mutation.SetResultQuantity(v)
	return _c
}

// SetNillableResultQuantity sets the "result_quantity" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableResultQuantity(v *int) *CraftingRecipeCreate {
	if v != nil {
		_c.SetResultQuantity(*v)
	}
	return _c
}

// SetResultDescription sets the "result_description" field.
func (_c *CraftingRecipeCreate) SetResultDescription(v string) *CraftingRecipeCreate {
	_c.mutation.SetResultDescription(v)
	return _c
}

// SetNillableResultDescription sets the "result_description" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableResultDescription(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetResultDescription(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *CraftingRecipeCreate) SetNotes(v string) *CraftingRecipeCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableNotes(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CraftingRecipeCreate) SetCreatedAt(v string) *CraftingRecipeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CraftingRecipeCreate) SetNillableCreatedAt(v *string) *CraftingRecipeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CraftingRecipeCreate) SetID(v int64) *CraftingRecipeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CraftingRecipeCreate) SetUser(v *User) *CraftingRecipeCreate {
	return _c.SetUserID(v.ID)
}

// AddCharacterCraftingIDs adds the "character_crafting" edge to the CharacterCrafting entity by IDs.
func (_c *CraftingRecipeCreate) AddCharacterCraftingIDs(ids ...int64) *CraftingRecipeCreate {
	_c.mutation.AddCharacterCraftingIDs(ids...)
	return _c
}

// AddCharacterCrafting adds the "character_crafting" edges to the CharacterCrafting entity.
func (_c *CraftingRecipeCreate) AddCharacterCrafting(v ...*CharacterCrafting) *CraftingRecipeCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCharacterCraftingIDs(ids...)
}

// Mutation returns the CraftingRecipeMutation object of the builder.
func (_c *CraftingRecipeCreate) Mutation() *CraftingRecipeMutation {
	return _c.mutation
}

// Save creates the CraftingRecipe in the database.
func (_c *CraftingRecipeCreate) Save(ctx context.Context) (*CraftingRecipe, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CraftingRecipeCreate) SaveX(ctx context.Context) *CraftingRecipe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CraftingRecipeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CraftingRecipeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CraftingRecipeCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := craftingrecipe.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Category(); !ok {
		v := craftingrecipe.DefaultCategory
		_c.mutation.SetCategory(v)
	}
	if _, ok := _c.mutation.DifficultyDc(); !ok {
		v := craftingrecipe.DefaultDifficultyDc
		_c.mutation.SetDifficultyDc(v)
	}
	if _, ok := _c.mutation.CraftingTimeHours(); !ok {
		v := craftingrecipe.DefaultCraftingTimeHours
		_c.mutation.SetCraftingTimeHours(v)
	}
	if _, ok := _c.mutation.RequiredTools(); !ok {
		v := craftingrecipe.DefaultRequiredTools
		_c.mutation.SetRequiredTools(v)
	}
	if _, ok := _c.mutation.RequiredMaterials(); !ok {
		v := craftingrecipe.DefaultRequiredMaterials
		_c.mutation.SetRequiredMaterials(v)
	}
	if _, ok := _c.mutation.ResultItemCategory(); !ok {
		v := craftingrecipe.DefaultResultItemCategory
		_c.mutation.SetResultItemCategory(v)
	}
	if _, ok := _c.mutation.ResultQuantity(); !ok {
		v := craftingrecipe.DefaultResultQuantity
		_c.mutation.SetResultQuantity(v)
	}
	if _, ok := _c.mutation.ResultDescription(); !ok {
		v := craftingrecipe.DefaultResultDescription
		_c.mutation.SetResultDescription(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := craftingrecipe.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := craftingrecipe.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CraftingRecipeCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CraftingRecipe.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "CraftingRecipe.description"`)}
	}
	if _, ok := _c.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "CraftingRecipe.category"`)}
	}
	if _, ok := _c.mutation.DifficultyDc(); !ok {
		return &ValidationError{Name: "difficulty_dc", err: errors.New(`ent: missing required field "CraftingRecipe.difficulty_dc"`)}
	}
	if _, ok := _c.mutation.CraftingTimeHours(); !ok {
		return &ValidationError{Name: "crafting_time_hours", err: errors.New(`ent: missing required field "CraftingRecipe.crafting_time_hours"`)}
	}
	if _, ok := _c.mutation.RequiredTools(); !ok {
		return &ValidationError{Name: "required_tools", err: errors.New(`ent: missing required field "CraftingRecipe.required_tools"`)}
	}
	if _, ok := _c.mutation.RequiredMaterials(); !ok {
		return &ValidationError{Name: "required_materials", err: errors.New(`ent: missing required field "CraftingRecipe.required_materials"`)}
	}
	if _, ok := _c.mutation.ResultItemName(); !ok {
		return &ValidationError{Name: "result_item_name", err: errors.New(`ent: missing required field "CraftingRecipe.result_item_name"`)}
	}
	if _, ok := _c.mutation.ResultItemCategory(); !ok {
		return &ValidationError{Name: "result_item_category", err: errors.New(`ent: missing required field "CraftingRecipe.result_item_category"`)}
	}
	if _, ok := _c.mutation.ResultQuantity(); !ok {
		return &ValidationError{Name: "result_quantity", err: errors.New(`ent: missing required field "CraftingRecipe.result_quantity"`)}
	}
	if _, ok := _c.mutation.ResultDescription(); !ok {
		return &ValidationError{Name: "result_description", err: errors.New(`ent: missing required field "CraftingRecipe.result_description"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "CraftingRecipe.notes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CraftingRecipe.created_at"`)}
	}
	return nil
}

func (_c *CraftingRecipeCreate) sqlSave(ctx context.Context) (*CraftingRecipe, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CraftingRecipeCreate) createSpec() (*CraftingRecipe, *sqlgraph.CreateSpec) {
	var (
		_node = &CraftingRecipe{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(craftingrecipe.Table, sqlgraph.NewFieldSpec(craftingrecipe.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(craftingrecipe.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(craftingrecipe.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Category(); ok {
		_spec.SetField(craftingrecipe.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := _c.mutation.DifficultyDc(); ok {
		_spec.SetField(craftingrecipe.FieldDifficultyDc, field.TypeInt, value)
		_node.DifficultyDc = value
	}
	if value, ok := _c.mutation.CraftingTimeHours(); ok {
		_spec.SetField(craftingrecipe.FieldCraftingTimeHours, field.TypeFloat64, value)
		_node.CraftingTimeHours = value
	}
	if value, ok := _c.mutation.RequiredTools(); ok {
		_spec.SetField(craftingrecipe.FieldRequiredTools, field.TypeString, value)
		_node.RequiredTools = value
	}
	if value, ok := _c.mutation.RequiredMaterials(); ok {
		_spec.SetField(craftingrecipe.FieldRequiredMaterials, field.TypeString, value)
		_node.RequiredMaterials = value
	}
	if value, ok := _c.mutation.ResultItemName(); ok {
		_spec.SetField(craftingrecipe.FieldResultItemName, field.TypeString, value)
		_node.ResultItemName = value
	}
	if value, ok := _c.mutation.ResultItemCategory(); ok {
		_spec.SetField(craftingrecipe.FieldResultItemCategory, field.TypeString, value)
		_node.ResultItemCategory = value
	}
	if value, ok := _c.mutation.ResultQuantity(); ok {
		_spec.SetField(craftingrecipe.FieldResultQuantity, field.TypeInt, value)
		_node.ResultQuantity = value
	}
	if value, ok := _c.mutation.ResultDescription(); ok {
		_spec.SetField(craftingrecipe.FieldResultDescription, field.TypeString, value)
		_node.ResultDescription = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(craftingrecipe.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(craftingrecipe.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   craftingrecipe.UserTable,
			Columns: []string{craftingrecipe.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CharacterCraftingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   craftingrecipe.CharacterCraftingTable,
			Columns: []string{craftingrecipe.CharacterCraftingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(charactercrafting.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CraftingRecipe.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CraftingRecipeUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CraftingRecipeCreate) OnConflict(opts ...sql.ConflictOption) *CraftingRecipeUpsertOne {
	_c.conflict = opts
	return &CraftingRecipeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CraftingRecipe.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CraftingRecipeCreate) OnConflictColumns(columns ...string) *CraftingRecipeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CraftingRecipeUpsertOne{
		create: _c,
	}
}

type (
	// CraftingRecipeUpsertOne is the builder for "upsert"-ing
	//  one CraftingRecipe node.
	CraftingRecipeUpsertOne struct {
		create *CraftingRecipeCreate
	}

	// CraftingRecipeUpsert is the "OnConflict" setter.
	CraftingRecipeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *CraftingRecipeUpsert) SetUserID(v int64) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateUserID() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *CraftingRecipeUpsert) ClearUserID() *CraftingRecipeUpsert {
	u.SetNull(craftingrecipe.FieldUserID)
	return u
}

// SetName sets the "name" field.
func (u *CraftingRecipeUpsert) SetName(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateName() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *CraftingRecipeUpsert) SetDescription(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateDescription() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldDescription)
	return u
}

// SetCategory sets the "category" field.
func (u *CraftingRecipeUpsert) SetCategory(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldCategory, v)
	return u
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateCategory() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldCategory)
	return u
}

// SetDifficultyDc sets the "difficulty_dc" field.
func (u *CraftingRecipeUpsert) SetDifficultyDc(v int) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldDifficultyDc, v)
	return u
}

// UpdateDifficultyDc sets the "difficulty_dc" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateDifficultyDc() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldDifficultyDc)
	return u
}

// AddDifficultyDc adds v to the "difficulty_dc" field.
func (u *CraftingRecipeUpsert) AddDifficultyDc(v int) *CraftingRecipeUpsert {
	u.Add(craftingrecipe.FieldDifficultyDc, v)
	return u
}

// SetCraftingTimeHours sets the "crafting_time_hours" field.
func (u *CraftingRecipeUpsert) SetCraftingTimeHours(v float64) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldCraftingTimeHours, v)
	return u
}

// UpdateCraftingTimeHours sets the "crafting_time_hours" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateCraftingTimeHours() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldCraftingTimeHours)
	return u
}

// AddCraftingTimeHours adds v to the "crafting_time_hours" field.
func (u *CraftingRecipeUpsert) AddCraftingTimeHours(v float64) *CraftingRecipeUpsert {
	u.Add(craftingrecipe.FieldCraftingTimeHours, v)
	return u
}

// SetRequiredTools sets the "required_tools" field.
func (u *CraftingRecipeUpsert) SetRequiredTools(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldRequiredTools, v)
	return u
}

// UpdateRequiredTools sets the "required_tools" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateRequiredTools() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldRequiredTools)
	return u
}

// SetRequiredMaterials sets the "required_materials" field.
func (u *CraftingRecipeUpsert) SetRequiredMaterials(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldRequiredMaterials, v)
	return u
}

// UpdateRequiredMaterials sets the "required_materials" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateRequiredMaterials() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldRequiredMaterials)
	return u
}

// SetResultItemName sets the "result_item_name" field.
func (u *CraftingRecipeUpsert) SetResultItemName(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldResultItemName, v)
	return u
}

// UpdateResultItemName sets the "result_item_name" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateResultItemName() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldResultItemName)
	return u
}

// SetResultItemCategory sets the "result_item_category" field.
func (u *CraftingRecipeUpsert) SetResultItemCategory(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldResultItemCategory, v)
	return u
}

// UpdateResultItemCategory sets the "result_item_category" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateResultItemCategory() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldResultItemCategory)
	return u
}

// SetResultQuantity sets the "result_quantity" field.
func (u *CraftingRecipeUpsert) SetResultQuantity(v int) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldResultQuantity, v)
	return u
}

// UpdateResultQuantity sets the "result_quantity" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateResultQuantity() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldResultQuantity)
	return u
}

// AddResultQuantity adds v to the "result_quantity" field.
func (u *CraftingRecipeUpsert) AddResultQuantity(v int) *CraftingRecipeUpsert {
	u.Add(craftingrecipe.FieldResultQuantity, v)
	return u
}

// SetResultDescription sets the "result_description" field.
func (u *CraftingRecipeUpsert) SetResultDescription(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldResultDescription, v)
	return u
}

// UpdateResultDescription sets the "result_description" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateResultDescription() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldResultDescription)
	return u
}

// SetNotes sets the "notes" field.
func (u *CraftingRecipeUpsert) SetNotes(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateNotes() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldNotes)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *CraftingRecipeUpsert) SetCreatedAt(v string) *CraftingRecipeUpsert {
	u.Set(craftingrecipe.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CraftingRecipeUpsert) UpdateCreatedAt() *CraftingRecipeUpsert {
	u.SetExcluded(craftingrecipe.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.CraftingRecipe.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(craftingrecipe.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CraftingRecipeUpsertOne) UpdateNewValues() *CraftingRecipeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(craftingrecipe.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CraftingRecipe.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CraftingRecipeUpsertOne) Ignore() *CraftingRecipeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CraftingRecipeUpsertOne) DoNothing() *CraftingRecipeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CraftingRecipeCreate.OnConflict
// documentation for more info.
func (u *CraftingRecipeUpsertOne) Update(set func(*CraftingRecipeUpsert)) *CraftingRecipeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CraftingRecipeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CraftingRecipeUpsertOne) SetUserID(v int64) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateUserID() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CraftingRecipeUpsertOne) ClearUserID() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.ClearUserID()
	})
}

// SetName sets the "name" field.
func (u *CraftingRecipeUpsertOne) SetName(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateName() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CraftingRecipeUpsertOne) SetDescription(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateDescription() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateDescription()
	})
}

// SetCategory sets the "category" field.
func (u *CraftingRecipeUpsertOne) SetCategory(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateCategory() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateCategory()
	})
}

// SetDifficultyDc sets the "difficulty_dc" field.
func (u *CraftingRecipeUpsertOne) SetDifficultyDc(v int) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetDifficultyDc(v)
	})
}

// AddDifficultyDc adds v to the "difficulty_dc" field.
func (u *CraftingRecipeUpsertOne) AddDifficultyDc(v int) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.AddDifficultyDc(v)
	})
}

// UpdateDifficultyDc sets the "difficulty_dc" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateDifficultyDc() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateDifficultyDc()
	})
}

// SetCraftingTimeHours sets the "crafting_time_hours" field.
func (u *CraftingRecipeUpsertOne) SetCraftingTimeHours(v float64) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetCraftingTimeHours(v)
	})
}

// AddCraftingTimeHours adds v to the "crafting_time_hours" field.
func (u *CraftingRecipeUpsertOne) AddCraftingTimeHours(v float64) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.AddCraftingTimeHours(v)
	})
}

// UpdateCraftingTimeHours sets the "crafting_time_hours" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateCraftingTimeHours() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateCraftingTimeHours()
	})
}

// SetRequiredTools sets the "required_tools" field.
func (u *CraftingRecipeUpsertOne) SetRequiredTools(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetRequiredTools(v)
	})
}

// UpdateRequiredTools sets the "required_tools" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateRequiredTools() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateRequiredTools()
	})
}

// SetRequiredMaterials sets the "required_materials" field.
func (u *CraftingRecipeUpsertOne) SetRequiredMaterials(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetRequiredMaterials(v)
	})
}

// UpdateRequiredMaterials sets the "required_materials" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateRequiredMaterials() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateRequiredMaterials()
	})
}

// SetResultItemName sets the "result_item_name" field.
func (u *CraftingRecipeUpsertOne) SetResultItemName(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultItemName(v)
	})
}

// UpdateResultItemName sets the "result_item_name" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateResultItemName() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultItemName()
	})
}

// SetResultItemCategory sets the "result_item_category" field.
func (u *CraftingRecipeUpsertOne) SetResultItemCategory(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultItemCategory(v)
	})
}

// UpdateResultItemCategory sets the "result_item_category" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateResultItemCategory() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultItemCategory()
	})
}

// SetResultQuantity sets the "result_quantity" field.
func (u *CraftingRecipeUpsertOne) SetResultQuantity(v int) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultQuantity(v)
	})
}

// AddResultQuantity adds v to the "result_quantity" field.
func (u *CraftingRecipeUpsertOne) AddResultQuantity(v int) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.AddResultQuantity(v)
	})
}

// UpdateResultQuantity sets the "result_quantity" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateResultQuantity() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultQuantity()
	})
}

// SetResultDescription sets the "result_description" field.
func (u *CraftingRecipeUpsertOne) SetResultDescription(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultDescription(v)
	})
}

// UpdateResultDescription sets the "result_description" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateResultDescription() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultDescription()
	})
}

// SetNotes sets the "notes" field.
func (u *CraftingRecipeUpsertOne) SetNotes(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateNotes() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateNotes()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CraftingRecipeUpsertOne) SetCreatedAt(v string) *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CraftingRecipeUpsertOne) UpdateCreatedAt() *CraftingRecipeUpsertOne {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CraftingRecipeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CraftingRecipeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CraftingRecipeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CraftingRecipeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CraftingRecipeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CraftingRecipeCreateBulk is the builder for creating many CraftingRecipe entities in bulk.
type CraftingRecipeCreateBulk struct {
	config
	err      error
	builders []*CraftingRecipeCreate
	conflict []sql.ConflictOption
}

// Save creates the CraftingRecipe entities in the database.
func (_c *CraftingRecipeCreateBulk) Save(ctx context.Context) ([]*CraftingRecipe, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CraftingRecipe, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CraftingRecipeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CraftingRecipeCreateBulk) SaveX(ctx context.Context) []*CraftingRecipe {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CraftingRecipeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CraftingRecipeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CraftingRecipe.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CraftingRecipeUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *CraftingRecipeCreateBulk) OnConflict(opts ...sql.ConflictOption) *CraftingRecipeUpsertBulk {
	_c.conflict = opts
	return &CraftingRecipeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CraftingRecipe.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CraftingRecipeCreateBulk) OnConflictColumns(columns ...string) *CraftingRecipeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CraftingRecipeUpsertBulk{
		create: _c,
	}
}

// CraftingRecipeUpsertBulk is the builder for "upsert"-ing
// a bulk of CraftingRecipe nodes.
type CraftingRecipeUpsertBulk struct {
	create *CraftingRecipeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CraftingRecipe.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(craftingrecipe.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CraftingRecipeUpsertBulk) UpdateNewValues() *CraftingRecipeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(craftingrecipe.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CraftingRecipe.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CraftingRecipeUpsertBulk) Ignore() *CraftingRecipeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CraftingRecipeUpsertBulk) DoNothing() *CraftingRecipeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CraftingRecipeCreateBulk.OnConflict
// documentation for more info.
func (u *CraftingRecipeUpsertBulk) Update(set func(*CraftingRecipeUpsert)) *CraftingRecipeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CraftingRecipeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *CraftingRecipeUpsertBulk) SetUserID(v int64) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateUserID() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *CraftingRecipeUpsertBulk) ClearUserID() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.ClearUserID()
	})
}

// SetName sets the "name" field.
func (u *CraftingRecipeUpsertBulk) SetName(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateName() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *CraftingRecipeUpsertBulk) SetDescription(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateDescription() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateDescription()
	})
}

// SetCategory sets the "category" field.
func (u *CraftingRecipeUpsertBulk) SetCategory(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetCategory(v)
	})
}

// UpdateCategory sets the "category" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateCategory() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateCategory()
	})
}

// SetDifficultyDc sets the "difficulty_dc" field.
func (u *CraftingRecipeUpsertBulk) SetDifficultyDc(v int) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetDifficultyDc(v)
	})
}

// AddDifficultyDc adds v to the "difficulty_dc" field.
func (u *CraftingRecipeUpsertBulk) AddDifficultyDc(v int) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.AddDifficultyDc(v)
	})
}

// UpdateDifficultyDc sets the "difficulty_dc" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateDifficultyDc() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateDifficultyDc()
	})
}

// SetCraftingTimeHours sets the "crafting_time_hours" field.
func (u *CraftingRecipeUpsertBulk) SetCraftingTimeHours(v float64) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetCraftingTimeHours(v)
	})
}

// AddCraftingTimeHours adds v to the "crafting_time_hours" field.
func (u *CraftingRecipeUpsertBulk) AddCraftingTimeHours(v float64) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.AddCraftingTimeHours(v)
	})
}

// UpdateCraftingTimeHours sets the "crafting_time_hours" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateCraftingTimeHours() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateCraftingTimeHours()
	})
}

// SetRequiredTools sets the "required_tools" field.
func (u *CraftingRecipeUpsertBulk) SetRequiredTools(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetRequiredTools(v)
	})
}

// UpdateRequiredTools sets the "required_tools" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateRequiredTools() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateRequiredTools()
	})
}

// SetRequiredMaterials sets the "required_materials" field.
func (u *CraftingRecipeUpsertBulk) SetRequiredMaterials(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetRequiredMaterials(v)
	})
}

// UpdateRequiredMaterials sets the "required_materials" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateRequiredMaterials() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateRequiredMaterials()
	})
}

// SetResultItemName sets the "result_item_name" field.
func (u *CraftingRecipeUpsertBulk) SetResultItemName(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultItemName(v)
	})
}

// UpdateResultItemName sets the "result_item_name" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateResultItemName() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultItemName()
	})
}

// SetResultItemCategory sets the "result_item_category" field.
func (u *CraftingRecipeUpsertBulk) SetResultItemCategory(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultItemCategory(v)
	})
}

// UpdateResultItemCategory sets the "result_item_category" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateResultItemCategory() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultItemCategory()
	})
}

// SetResultQuantity sets the "result_quantity" field.
func (u *CraftingRecipeUpsertBulk) SetResultQuantity(v int) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultQuantity(v)
	})
}

// AddResultQuantity adds v to the "result_quantity" field.
func (u *CraftingRecipeUpsertBulk) AddResultQuantity(v int) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.AddResultQuantity(v)
	})
}

// UpdateResultQuantity sets the "result_quantity" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateResultQuantity() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultQuantity()
	})
}

// SetResultDescription sets the "result_description" field.
func (u *CraftingRecipeUpsertBulk) SetResultDescription(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetResultDescription(v)
	})
}

// UpdateResultDescription sets the "result_description" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateResultDescription() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateResultDescription()
	})
}

// SetNotes sets the "notes" field.
func (u *CraftingRecipeUpsertBulk) SetNotes(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateNotes() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateNotes()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *CraftingRecipeUpsertBulk) SetCreatedAt(v string) *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *CraftingRecipeUpsertBulk) UpdateCreatedAt() *CraftingRecipeUpsertBulk {
	return u.Update(func(s *CraftingRecipeUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *CraftingRecipeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CraftingRecipeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CraftingRecipeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CraftingRecipeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
