// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"villum/ent/campaign"
	"villum/ent/encountertemplate"
	"villum/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// EncounterTemplate is the model entity for the EncounterTemplate schema.
type EncounterTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CampaignID holds the value of the "campaign_id" field.
	CampaignID int64 `json:"campaign_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Environment holds the value of the "environment" field.
	Environment string `json:"environment,omitempty"`
	// Difficulty holds the value of the "difficulty" field.
	Difficulty string `json:"difficulty,omitempty"`
	// XpBudget holds the value of the "xp_budget" field.
	XpBudget int `json:"xp_budget,omitempty"`
	// TotalXp holds the value of the "total_xp" field.
	TotalXp int `json:"total_xp,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EncounterTemplateQuery when eager-loading is set.
	Edges        EncounterTemplateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EncounterTemplateEdges holds the relations/edges for other nodes in the graph.
type EncounterTemplateEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Campaign holds the value of the campaign edge.
	Campaign *Campaign `json:"campaign,omitempty"`
	// Monsters holds the value of the monsters edge.
	Monsters []*EncounterMonster `json:"monsters,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EncounterTemplateEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// CampaignOrErr returns the Campaign value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EncounterTemplateEdges) CampaignOrErr() (*Campaign, error) {
	if e.Campaign != nil {
		return e.Campaign, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: campaign.Label}
	}
	return nil, &NotLoadedError{edge: "campaign"}
}

// MonstersOrErr returns the Monsters value or an error if the edge
// was not loaded in eager-loading.
func (e EncounterTemplateEdges) MonstersOrErr() ([]*EncounterMonster, error) {
	if e.loadedTypes[2] {
		return e.Monsters, nil
	}
	return nil, &NotLoadedError{edge: "monsters"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EncounterTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case encountertemplate.FieldID, encountertemplate.FieldCampaignID, encountertemplate.FieldUserID, encountertemplate.FieldXpBudget, encountertemplate.FieldTotalXp:
			values[i] = new(sql.NullInt64)
		case encountertemplate.FieldName, encountertemplate.FieldDescription, encountertemplate.FieldEnvironment, encountertemplate.FieldDifficulty, encountertemplate.FieldNotes, encountertemplate.FieldCreatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EncounterTemplate fields.
func (_m *EncounterTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case encountertemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case encountertemplate.FieldCampaignID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_id", values[i])
			} else if value.Valid {
				_m.CampaignID = value.Int64
			}
		case encountertemplate.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case encountertemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case encountertemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case encountertemplate.FieldEnvironment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value.Valid {
				_m.Environment = value.String
			}
		case encountertemplate.FieldDifficulty:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field difficulty", values[i])
			} else if value.Valid {
				_m.Difficulty = value.String
			}
		case encountertemplate.FieldXpBudget:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field xp_budget", values[i])
			} else if value.Valid {
				_m.XpBudget = int(value.Int64)
			}
		case encountertemplate.FieldTotalXp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_xp", values[i])
			} else if value.Valid {
				_m.TotalXp = int(value.Int64)
			}
		case encountertemplate.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case encountertemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EncounterTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *EncounterTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the EncounterTemplate entity.
func (_m *EncounterTemplate) QueryUser() *UserQuery {
	return NewEncounterTemplateClient(_m.config).QueryUser(_m)
}

// QueryCampaign queries the "campaign" edge of the EncounterTemplate entity.
func (_m *EncounterTemplate) QueryCampaign() *CampaignQuery {
	return NewEncounterTemplateClient(_m.config).QueryCampaign(_m)
}

// QueryMonsters queries the "monsters" edge of the EncounterTemplate entity.
func (_m *EncounterTemplate) QueryMonsters() *EncounterMonsterQuery {
	return NewEncounterTemplateClient(_m.config).QueryMonsters(_m)
}

// Update returns a builder for updating this EncounterTemplate.
// Note that you need to call EncounterTemplate.Unwrap() before calling this method if this EncounterTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EncounterTemplate) Update() *EncounterTemplateUpdateOne {
	return NewEncounterTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EncounterTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EncounterTemplate) Unwrap() *EncounterTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EncounterTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EncounterTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("EncounterTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("campaign_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CampaignID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(_m.Environment)
	builder.WriteString(", ")
	builder.WriteString("difficulty=")
	builder.WriteString(_m.Difficulty)
	builder.WriteString(", ")
	builder.WriteString("xp_budget=")
	builder.WriteString(fmt.Sprintf("%v", _m.XpBudget))
	builder.WriteString(", ")
	builder.WriteString("total_xp=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalXp))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// EncounterTemplates is a parsable slice of EncounterTemplate.
type EncounterTemplates []*EncounterTemplate
