// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"villum/ent/encountertemplate"
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EncounterTemplateDelete is the builder for deleting a EncounterTemplate entity.
type EncounterTemplateDelete struct {
	config
	hooks    []Hook
	mutation *EncounterTemplateMutation
}

// Where appends a list predicates to the EncounterTemplateDelete builder.
func (_d *EncounterTemplateDelete) Where(ps ...predicate.EncounterTemplate) *EncounterTemplateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *EncounterTemplateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EncounterTemplateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *EncounterTemplateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(encountertemplate.Table, sqlgraph.NewFieldSpec(encountertemplate.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// EncounterTemplateDeleteOne is the builder for deleting a single EncounterTemplate entity.
type EncounterTemplateDeleteOne struct {
	_d *EncounterTemplateDelete
}

// Where appends a list predicates to the EncounterTemplateDelete builder.
func (_d *EncounterTemplateDeleteOne) Where(ps ...predicate.EncounterTemplate) *EncounterTemplateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *EncounterTemplateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{encountertemplate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *EncounterTemplateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
