// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/character"
	"villum/ent/journalentry"
	"villum/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JournalEntryUpdate is the builder for updating JournalEntry entities.
type JournalEntryUpdate struct {
	config
	hooks    []Hook
	mutation *JournalEntryMutation
}

// Where appends a list predicates to the JournalEntryUpdate builder.
func (_u *JournalEntryUpdate) Where(ps ...predicate.JournalEntry) *JournalEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCharacterID sets the "character_id" field.
func (_u *JournalEntryUpdate) SetCharacterID(v int64) *JournalEntryUpdate {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *JournalEntryUpdate) SetNillableCharacterID(v *int64) *JournalEntryUpdate {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *JournalEntryUpdate) SetTitle(v string) *JournalEntryUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *JournalEntryUpdate) SetNillableTitle(v *string) *JournalEntryUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetEntry sets the "entry" field.
func (_u *JournalEntryUpdate) SetEntry(v string) *JournalEntryUpdate {
	_u.mutation.SetEntry(v)
	return _u
}

// SetNillableEntry sets the "entry" field if the given value is not nil.
func (_u *JournalEntryUpdate) SetNillableEntry(v *string) *JournalEntryUpdate {
	if v != nil {
		_u.SetEntry(*v)
	}
	return _u
}

// SetEntryDate sets the "entry_date" field.
func (_u *JournalEntryUpdate) SetEntryDate(v string) *JournalEntryUpdate {
	_u.mutation.SetEntryDate(v)
	return _u
}

// SetNillableEntryDate sets the "entry_date" field if the given value is not nil.
func (_u *JournalEntryUpdate) SetNillableEntryDate(v *string) *JournalEntryUpdate {
	if v != nil {
		_u.SetEntryDate(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JournalEntryUpdate) SetCreatedAt(v string) *JournalEntryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JournalEntryUpdate) SetNillableCreatedAt(v *string) *JournalEntryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *JournalEntryUpdate) SetCharacter(v *Character) *JournalEntryUpdate {
	return _u.SetCharacterID(v.ID)
}

// Mutation returns the JournalEntryMutation object of the builder.
func (_u *JournalEntryUpdate) Mutation() *JournalEntryMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *JournalEntryUpdate) ClearCharacter() *JournalEntryUpdate {
	_u.mutation.ClearCharacter()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JournalEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JournalEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JournalEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JournalEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JournalEntryUpdate) check() error {
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JournalEntry.character"`)
	}
	return nil
}

func (_u *JournalEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(journalentry.Table, journalentry.Columns, sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(journalentry.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Entry(); ok {
		_spec.SetField(journalentry.FieldEntry, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryDate(); ok {
		_spec.SetField(journalentry.FieldEntryDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(journalentry.FieldCreatedAt, field.TypeString, value)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.CharacterTable,
			Columns: []string{journalentry.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.CharacterTable,
			Columns: []string{journalentry.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journalentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JournalEntryUpdateOne is the builder for updating a single JournalEntry entity.
type JournalEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JournalEntryMutation
}

// SetCharacterID sets the "character_id" field.
func (_u *JournalEntryUpdateOne) SetCharacterID(v int64) *JournalEntryUpdateOne {
	_u.mutation.SetCharacterID(v)
	return _u
}

// SetNillableCharacterID sets the "character_id" field if the given value is not nil.
func (_u *JournalEntryUpdateOne) SetNillableCharacterID(v *int64) *JournalEntryUpdateOne {
	if v != nil {
		_u.SetCharacterID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *JournalEntryUpdateOne) SetTitle(v string) *JournalEntryUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *JournalEntryUpdateOne) SetNillableTitle(v *string) *JournalEntryUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetEntry sets the "entry" field.
func (_u *JournalEntryUpdateOne) SetEntry(v string) *JournalEntryUpdateOne {
	_u.mutation.SetEntry(v)
	return _u
}

// SetNillableEntry sets the "entry" field if the given value is not nil.
func (_u *JournalEntryUpdateOne) SetNillableEntry(v *string) *JournalEntryUpdateOne {
	if v != nil {
		_u.SetEntry(*v)
	}
	return _u
}

// SetEntryDate sets the "entry_date" field.
func (_u *JournalEntryUpdateOne) SetEntryDate(v string) *JournalEntryUpdateOne {
	_u.mutation.SetEntryDate(v)
	return _u
}

// SetNillableEntryDate sets the "entry_date" field if the given value is not nil.
func (_u *JournalEntryUpdateOne) SetNillableEntryDate(v *string) *JournalEntryUpdateOne {
	if v != nil {
		_u.SetEntryDate(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JournalEntryUpdateOne) SetCreatedAt(v string) *JournalEntryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JournalEntryUpdateOne) SetNillableCreatedAt(v *string) *JournalEntryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetCharacter sets the "character" edge to the Character entity.
func (_u *JournalEntryUpdateOne) SetCharacter(v *Character) *JournalEntryUpdateOne {
	return _u.SetCharacterID(v.ID)
}

// Mutation returns the JournalEntryMutation object of the builder.
func (_u *JournalEntryUpdateOne) Mutation() *JournalEntryMutation {
	return _u.mutation
}

// ClearCharacter clears the "character" edge to the Character entity.
func (_u *JournalEntryUpdateOne) ClearCharacter() *JournalEntryUpdateOne {
	_u.mutation.ClearCharacter()
	return _u
}

// Where appends a list predicates to the JournalEntryUpdate builder.
func (_u *JournalEntryUpdateOne) Where(ps ...predicate.JournalEntry) *JournalEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JournalEntryUpdateOne) Select(field string, fields ...string) *JournalEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated JournalEntry entity.
func (_u *JournalEntryUpdateOne) Save(ctx context.Context) (*JournalEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JournalEntryUpdateOne) SaveX(ctx context.Context) *JournalEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JournalEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JournalEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *JournalEntryUpdateOne) check() error {
	if _u.mutation.CharacterCleared() && len(_u.mutation.CharacterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "JournalEntry.character"`)
	}
	return nil
}

func (_u *JournalEntryUpdateOne) sqlSave(ctx context.Context) (_node *JournalEntry, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(journalentry.Table, journalentry.Columns, sqlgraph.NewFieldSpec(journalentry.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "JournalEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, journalentry.FieldID)
		for _, f := range fields {
			if !journalentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != journalentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(journalentry.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Entry(); ok {
		_spec.SetField(journalentry.FieldEntry, field.TypeString, value)
	}
	if value, ok := _u.mutation.EntryDate(); ok {
		_spec.SetField(journalentry.FieldEntryDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(journalentry.FieldCreatedAt, field.TypeString, value)
	}
	if _u.mutation.CharacterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.CharacterTable,
			Columns: []string{journalentry.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   journalentry.CharacterTable,
			Columns: []string{journalentry.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &JournalEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journalentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
