// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/oneshotactnpc"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OneShotActNPCCreate is the builder for creating a OneShotActNPC entity.
type OneShotActNPCCreate struct {
	config
	mutation *OneShotActNPCMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActID sets the "act_id" field.
func (_c *OneShotActNPCCreate) SetActID(v int64) *OneShotActNPCCreate {
	_c.mutation.SetActID(v)
	return _c
}

// SetNpcID sets the "npc_id" field.
func (_c *OneShotActNPCCreate) SetNpcID(v int64) *OneShotActNPCCreate {
	_c.mutation.SetNpcID(v)
	return _c
}

// SetNillableNpcID sets the "npc_id" field if the given value is not nil.
func (_c *OneShotActNPCCreate) SetNillableNpcID(v *int64) *OneShotActNPCCreate {
	if v != nil {
		_c.SetNpcID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *OneShotActNPCCreate) SetName(v string) *OneShotActNPCCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *OneShotActNPCCreate) SetNillableName(v *string) *OneShotActNPCCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *OneShotActNPCCreate) SetRole(v string) *OneShotActNPCCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *OneShotActNPCCreate) SetNillableRole(v *string) *OneShotActNPCCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *OneShotActNPCCreate) SetNotes(v string) *OneShotActNPCCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *OneShotActNPCCreate) SetNillableNotes(v *string) *OneShotActNPCCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetIsInline sets the "is_inline" field.
func (_c *OneShotActNPCCreate) SetIsInline(v bool) *OneShotActNPCCreate {
	_c.mutation.SetIsInline(v)
	return _c
}

// SetNillableIsInline sets the "is_inline" field if the given value is not nil.
func (_c *OneShotActNPCCreate) SetNillableIsInline(v *bool) *OneShotActNPCCreate {
	if v != nil {
		_c.SetIsInline(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OneShotActNPCCreate) SetCreatedAt(v string) *OneShotActNPCCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OneShotActNPCCreate) SetNillableCreatedAt(v *string) *OneShotActNPCCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OneShotActNPCCreate) SetID(v int64) *OneShotActNPCCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the OneShotActNPCMutation object of the builder.
func (_c *OneShotActNPCCreate) Mutation() *OneShotActNPCMutation {
	return _c.mutation
}

// Save creates the OneShotActNPC in the database.
func (_c *OneShotActNPCCreate) Save(ctx context.Context) (*OneShotActNPC, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OneShotActNPCCreate) SaveX(ctx context.Context) *OneShotActNPC {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OneShotActNPCCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OneShotActNPCCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OneShotActNPCCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := oneshotactnpc.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := oneshotactnpc.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := oneshotactnpc.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.IsInline(); !ok {
		v := oneshotactnpc.DefaultIsInline
		_c.mutation.SetIsInline(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oneshotactnpc.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OneShotActNPCCreate) check() error {
	if _, ok := _c.mutation.ActID(); !ok {
		return &ValidationError{Name: "act_id", err: errors.New(`ent: missing required field "OneShotActNPC.act_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OneShotActNPC.name"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "OneShotActNPC.role"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "OneShotActNPC.notes"`)}
	}
	if _, ok := _c.mutation.IsInline(); !ok {
		return &ValidationError{Name: "is_inline", err: errors.New(`ent: missing required field "OneShotActNPC.is_inline"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OneShotActNPC.created_at"`)}
	}
	return nil
}

func (_c *OneShotActNPCCreate) sqlSave(ctx context.Context) (*OneShotActNPC, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OneShotActNPCCreate) createSpec() (*OneShotActNPC, *sqlgraph.CreateSpec) {
	var (
		_node = &OneShotActNPC{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oneshotactnpc.Table, sqlgraph.NewFieldSpec(oneshotactnpc.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ActID(); ok {
		_spec.SetField(oneshotactnpc.FieldActID, field.TypeInt64, value)
		_node.ActID = value
	}
	if value, ok := _c.mutation.NpcID(); ok {
		_spec.SetField(oneshotactnpc.FieldNpcID, field.TypeInt64, value)
		_node.NpcID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oneshotactnpc.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(oneshotactnpc.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(oneshotactnpc.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.IsInline(); ok {
		_spec.SetField(oneshotactnpc.FieldIsInline, field.TypeBool, value)
		_node.IsInline = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oneshotactnpc.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OneShotActNPC.Create().
//		SetActID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OneShotActNPCUpsert) {
//			SetActID(v+v).
//		}).
//		Exec(ctx)
func (_c *OneShotActNPCCreate) OnConflict(opts ...sql.ConflictOption) *OneShotActNPCUpsertOne {
	_c.conflict = opts
	return &OneShotActNPCUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OneShotActNPC.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OneShotActNPCCreate) OnConflictColumns(columns ...string) *OneShotActNPCUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OneShotActNPCUpsertOne{
		create: _c,
	}
}

type (
	// OneShotActNPCUpsertOne is the builder for "upsert"-ing
	//  one OneShotActNPC node.
	OneShotActNPCUpsertOne struct {
		create *OneShotActNPCCreate
	}

	// OneShotActNPCUpsert is the "OnConflict" setter.
	OneShotActNPCUpsert struct {
		*sql.UpdateSet
	}
)

// SetActID sets the "act_id" field.
func (u *OneShotActNPCUpsert) SetActID(v int64) *OneShotActNPCUpsert {
	u.Set(oneshotactnpc.FieldActID, v)
	return u
}

// UpdateActID sets the "act_id" field to the value that was provided on create.
func (u *OneShotActNPCUpsert) UpdateActID() *OneShotActNPCUpsert {
	u.SetExcluded(oneshotactnpc.FieldActID)
	return u
}

// AddActID adds v to the "act_id" field.
func (u *OneShotActNPCUpsert) AddActID(v int64) *OneShotActNPCUpsert {
	u.Add(oneshotactnpc.FieldActID, v)
	return u
}

// SetNpcID sets the "npc_id" field.
func (u *OneShotActNPCUpsert) SetNpcID(v int64) *OneShotActNPCUpsert {
	u.Set(oneshotactnpc.FieldNpcID, v)
	return u
}

// UpdateNpcID sets the "npc_id" field to the value that was provided on create.
func (u *OneShotActNPCUpsert) UpdateNpcID() *OneShotActNPCUpsert {
	u.SetExcluded(oneshotactnpc.FieldNpcID)
	return u
}

// AddNpcID adds v to the "npc_id" field.
func (u *OneShotActNPCUpsert) AddNpcID(v int64) *OneShotActNPCUpsert {
	u.Add(oneshotactnpc.FieldNpcID, v)
	return u
}

// ClearNpcID clears the value of the "npc_id" field.
func (u *OneShotActNPCUpsert) ClearNpcID() *OneShotActNPCUpsert {
	u.SetNull(oneshotactnpc.FieldNpcID)
	return u
}

// SetName sets the "name" field.
func (u *OneShotActNPCUpsert) SetName(v string) *OneShotActNPCUpsert {
	u.Set(oneshotactnpc.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OneShotActNPCUpsert) UpdateName() *OneShotActNPCUpsert {
	u.SetExcluded(oneshotactnpc.FieldName)
	return u
}

// SetRole sets the "role" field.
func (u *OneShotActNPCUpsert) SetRole(v string) *OneShotActNPCUpsert {
	u.Set(oneshotactnpc.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OneShotActNPCUpsert) UpdateRole() *OneShotActNPCUpsert {
	u.SetExcluded(oneshotactnpc.FieldRole)
	return u
}

// SetNotes sets the "notes" field.
func (u *OneShotActNPCUpsert) SetNotes(v string) *OneShotActNPCUpsert {
	u.Set(oneshotactnpc.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OneShotActNPCUpsert) UpdateNotes() *OneShotActNPCUpsert {
	u.SetExcluded(oneshotactnpc.FieldNotes)
	return u
}

// SetIsInline sets the "is_inline" field.
func (u *OneShotActNPCUpsert) SetIsInline(v bool) *OneShotActNPCUpsert {
	u.Set(oneshotactnpc.FieldIsInline, v)
	return u
}

// UpdateIsInline sets the "is_inline" field to the value that was provided on create.
func (u *OneShotActNPCUpsert) UpdateIsInline() *OneShotActNPCUpsert {
	u.SetExcluded(oneshotactnpc.FieldIsInline)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *OneShotActNPCUpsert) SetCreatedAt(v string) *OneShotActNPCUpsert {
	u.Set(oneshotactnpc.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OneShotActNPCUpsert) UpdateCreatedAt() *OneShotActNPCUpsert {
	u.SetExcluded(oneshotactnpc.FieldCreatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.OneShotActNPC.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oneshotactnpc.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OneShotActNPCUpsertOne) UpdateNewValues() *OneShotActNPCUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(oneshotactnpc.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OneShotActNPC.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OneShotActNPCUpsertOne) Ignore() *OneShotActNPCUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OneShotActNPCUpsertOne) DoNothing() *OneShotActNPCUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OneShotActNPCCreate.OnConflict
// documentation for more info.
func (u *OneShotActNPCUpsertOne) Update(set func(*OneShotActNPCUpsert)) *OneShotActNPCUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OneShotActNPCUpsert{UpdateSet: update})
	}))
	return u
}

// SetActID sets the "act_id" field.
func (u *OneShotActNPCUpsertOne) SetActID(v int64) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetActID(v)
	})
}

// AddActID adds v to the "act_id" field.
func (u *OneShotActNPCUpsertOne) AddActID(v int64) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.AddActID(v)
	})
}

// UpdateActID sets the "act_id" field to the value that was provided on create.
func (u *OneShotActNPCUpsertOne) UpdateActID() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateActID()
	})
}

// SetNpcID sets the "npc_id" field.
func (u *OneShotActNPCUpsertOne) SetNpcID(v int64) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetNpcID(v)
	})
}

// AddNpcID adds v to the "npc_id" field.
func (u *OneShotActNPCUpsertOne) AddNpcID(v int64) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.AddNpcID(v)
	})
}

// UpdateNpcID sets the "npc_id" field to the value that was provided on create.
func (u *OneShotActNPCUpsertOne) UpdateNpcID() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateNpcID()
	})
}

// ClearNpcID clears the value of the "npc_id" field.
func (u *OneShotActNPCUpsertOne) ClearNpcID() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.ClearNpcID()
	})
}

// SetName sets the "name" field.
func (u *OneShotActNPCUpsertOne) SetName(v string) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OneShotActNPCUpsertOne) UpdateName() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateName()
	})
}

// SetRole sets the "role" field.
func (u *OneShotActNPCUpsertOne) SetRole(v string) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OneShotActNPCUpsertOne) UpdateRole() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateRole()
	})
}

// SetNotes sets the "notes" field.
func (u *OneShotActNPCUpsertOne) SetNotes(v string) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OneShotActNPCUpsertOne) UpdateNotes() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateNotes()
	})
}

// SetIsInline sets the "is_inline" field.
func (u *OneShotActNPCUpsertOne) SetIsInline(v bool) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetIsInline(v)
	})
}

// UpdateIsInline sets the "is_inline" field to the value that was provided on create.
func (u *OneShotActNPCUpsertOne) UpdateIsInline() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateIsInline()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OneShotActNPCUpsertOne) SetCreatedAt(v string) *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OneShotActNPCUpsertOne) UpdateCreatedAt() *OneShotActNPCUpsertOne {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *OneShotActNPCUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OneShotActNPCCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OneShotActNPCUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OneShotActNPCUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OneShotActNPCUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OneShotActNPCCreateBulk is the builder for creating many OneShotActNPC entities in bulk.
type OneShotActNPCCreateBulk struct {
	config
	err      error
	builders []*OneShotActNPCCreate
	conflict []sql.ConflictOption
}

// Save creates the OneShotActNPC entities in the database.
func (_c *OneShotActNPCCreateBulk) Save(ctx context.Context) ([]*OneShotActNPC, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OneShotActNPC, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OneShotActNPCMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OneShotActNPCCreateBulk) SaveX(ctx context.Context) []*OneShotActNPC {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OneShotActNPCCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OneShotActNPCCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OneShotActNPC.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OneShotActNPCUpsert) {
//			SetActID(v+v).
//		}).
//		Exec(ctx)
func (_c *OneShotActNPCCreateBulk) OnConflict(opts ...sql.ConflictOption) *OneShotActNPCUpsertBulk {
	_c.conflict = opts
	return &OneShotActNPCUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OneShotActNPC.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OneShotActNPCCreateBulk) OnConflictColumns(columns ...string) *OneShotActNPCUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OneShotActNPCUpsertBulk{
		create: _c,
	}
}

// OneShotActNPCUpsertBulk is the builder for "upsert"-ing
// a bulk of OneShotActNPC nodes.
type OneShotActNPCUpsertBulk struct {
	create *OneShotActNPCCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OneShotActNPC.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(oneshotactnpc.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *OneShotActNPCUpsertBulk) UpdateNewValues() *OneShotActNPCUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(oneshotactnpc.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OneShotActNPC.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OneShotActNPCUpsertBulk) Ignore() *OneShotActNPCUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OneShotActNPCUpsertBulk) DoNothing() *OneShotActNPCUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OneShotActNPCCreateBulk.OnConflict
// documentation for more info.
func (u *OneShotActNPCUpsertBulk) Update(set func(*OneShotActNPCUpsert)) *OneShotActNPCUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OneShotActNPCUpsert{UpdateSet: update})
	}))
	return u
}

// SetActID sets the "act_id" field.
func (u *OneShotActNPCUpsertBulk) SetActID(v int64) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetActID(v)
	})
}

// AddActID adds v to the "act_id" field.
func (u *OneShotActNPCUpsertBulk) AddActID(v int64) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.AddActID(v)
	})
}

// UpdateActID sets the "act_id" field to the value that was provided on create.
func (u *OneShotActNPCUpsertBulk) UpdateActID() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateActID()
	})
}

// SetNpcID sets the "npc_id" field.
func (u *OneShotActNPCUpsertBulk) SetNpcID(v int64) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetNpcID(v)
	})
}

// AddNpcID adds v to the "npc_id" field.
func (u *OneShotActNPCUpsertBulk) AddNpcID(v int64) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.AddNpcID(v)
	})
}

// UpdateNpcID sets the "npc_id" field to the value that was provided on create.
func (u *OneShotActNPCUpsertBulk) UpdateNpcID() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateNpcID()
	})
}

// ClearNpcID clears the value of the "npc_id" field.
func (u *OneShotActNPCUpsertBulk) ClearNpcID() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.ClearNpcID()
	})
}

// SetName sets the "name" field.
func (u *OneShotActNPCUpsertBulk) SetName(v string) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OneShotActNPCUpsertBulk) UpdateName() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateName()
	})
}

// SetRole sets the "role" field.
func (u *OneShotActNPCUpsertBulk) SetRole(v string) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *OneShotActNPCUpsertBulk) UpdateRole() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateRole()
	})
}

// SetNotes sets the "notes" field.
func (u *OneShotActNPCUpsertBulk) SetNotes(v string) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OneShotActNPCUpsertBulk) UpdateNotes() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateNotes()
	})
}

// SetIsInline sets the "is_inline" field.
func (u *OneShotActNPCUpsertBulk) SetIsInline(v bool) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetIsInline(v)
	})
}

// UpdateIsInline sets the "is_inline" field to the value that was provided on create.
func (u *OneShotActNPCUpsertBulk) UpdateIsInline() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateIsInline()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OneShotActNPCUpsertBulk) SetCreatedAt(v string) *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OneShotActNPCUpsertBulk) UpdateCreatedAt() *OneShotActNPCUpsertBulk {
	return u.Update(func(s *OneShotActNPCUpsert) {
		s.UpdateCreatedAt()
	})
}

// Exec executes the query.
func (u *OneShotActNPCUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OneShotActNPCCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OneShotActNPCCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OneShotActNPCUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
