// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"villum/ent/otelsetting"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// OTelSetting is the model entity for the OTelSetting schema.
type OTelSetting struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled      bool `json:"enabled,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OTelSetting) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case otelsetting.FieldEnabled:
			values[i] = new(sql.NullBool)
		case otelsetting.FieldID:
			values[i] = new(sql.NullInt64)
		case otelsetting.FieldEndpoint:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OTelSetting fields.
func (_m *OTelSetting) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case otelsetting.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case otelsetting.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case otelsetting.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OTelSetting.
// This includes values selected through modifiers, order, etc.
func (_m *OTelSetting) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OTelSetting.
// Note that you need to call OTelSetting.Unwrap() before calling this method if this OTelSetting
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OTelSetting) Update() *OTelSettingUpdateOne {
	return NewOTelSettingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OTelSetting entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OTelSetting) Unwrap() *OTelSetting {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OTelSetting is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OTelSetting) String() string {
	var builder strings.Builder
	builder.WriteString("OTelSetting(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// OTelSettings is a parsable slice of OTelSetting.
type OTelSettings []*OTelSetting
