// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/character"
	"villum/ent/quest"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestCreate is the builder for creating a Quest entity.
type QuestCreate struct {
	config
	mutation *QuestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCharacterID sets the "character_id" field.
func (_c *QuestCreate) SetCharacterID(v int64) *QuestCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *QuestCreate) SetName(v string) *QuestCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *QuestCreate) SetDescription(v string) *QuestCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *QuestCreate) SetNillableDescription(v *string) *QuestCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *QuestCreate) SetStatus(v string) *QuestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *QuestCreate) SetNillableStatus(v *string) *QuestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetObjectives sets the "objectives" field.
func (_c *QuestCreate) SetObjectives(v string) *QuestCreate {
	_c.mutation.SetObjectives(v)
	return _c
}

// SetNillableObjectives sets the "objectives" field if the given value is not nil.
func (_c *QuestCreate) SetNillableObjectives(v *string) *QuestCreate {
	if v != nil {
		_c.SetObjectives(*v)
	}
	return _c
}

// SetRewards sets the "rewards" field.
func (_c *QuestCreate) SetRewards(v string) *QuestCreate {
	_c.mutation.SetRewards(v)
	return _c
}

// SetNillableRewards sets the "rewards" field if the given value is not nil.
func (_c *QuestCreate) SetNillableRewards(v *string) *QuestCreate {
	if v != nil {
		_c.SetRewards(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *QuestCreate) SetNotes(v string) *QuestCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *QuestCreate) SetNillableNotes(v *string) *QuestCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QuestCreate) SetCreatedAt(v string) *QuestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QuestCreate) SetNillableCreatedAt(v *string) *QuestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QuestCreate) SetUpdatedAt(v string) *QuestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QuestCreate) SetNillableUpdatedAt(v *string) *QuestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QuestCreate) SetID(v int64) *QuestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCharacter sets the "character" edge to the Character entity.
func (_c *QuestCreate) SetCharacter(v *Character) *QuestCreate {
	return _c.SetCharacterID(v.ID)
}

// Mutation returns the QuestMutation object of the builder.
func (_c *QuestCreate) Mutation() *QuestMutation {
	return _c.mutation
}

// Save creates the Quest in the database.
func (_c *QuestCreate) Save(ctx context.Context) (*Quest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuestCreate) SaveX(ctx context.Context) *Quest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuestCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := quest.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := quest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Objectives(); !ok {
		v := quest.DefaultObjectives
		_c.mutation.SetObjectives(v)
	}
	if _, ok := _c.mutation.Rewards(); !ok {
		v := quest.DefaultRewards
		_c.mutation.SetRewards(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := quest.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := quest.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := quest.DefaultUpdatedAt
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuestCreate) check() error {
	if _, ok := _c.mutation.CharacterID(); !ok {
		return &ValidationError{Name: "character_id", err: errors.New(`ent: missing required field "Quest.character_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Quest.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Quest.description"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Quest.status"`)}
	}
	if _, ok := _c.mutation.Objectives(); !ok {
		return &ValidationError{Name: "objectives", err: errors.New(`ent: missing required field "Quest.objectives"`)}
	}
	if _, ok := _c.mutation.Rewards(); !ok {
		return &ValidationError{Name: "rewards", err: errors.New(`ent: missing required field "Quest.rewards"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "Quest.notes"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Quest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Quest.updated_at"`)}
	}
	if len(_c.mutation.CharacterIDs()) == 0 {
		return &ValidationError{Name: "character", err: errors.New(`ent: missing required edge "Quest.character"`)}
	}
	return nil
}

func (_c *QuestCreate) sqlSave(ctx context.Context) (*Quest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuestCreate) createSpec() (*Quest, *sqlgraph.CreateSpec) {
	var (
		_node = &Quest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quest.Table, sqlgraph.NewFieldSpec(quest.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(quest.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(quest.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(quest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Objectives(); ok {
		_spec.SetField(quest.FieldObjectives, field.TypeString, value)
		_node.Objectives = value
	}
	if value, ok := _c.mutation.Rewards(); ok {
		_spec.SetField(quest.FieldRewards, field.TypeString, value)
		_node.Rewards = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(quest.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(quest.FieldCreatedAt, field.TypeString, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(quest.FieldUpdatedAt, field.TypeString, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.CharacterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   quest.CharacterTable,
			Columns: []string{quest.CharacterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(character.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CharacterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Quest.Create().
//		SetCharacterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuestUpsert) {
//			SetCharacterID(v+v).
//		}).
//		Exec(ctx)
func (_c *QuestCreate) OnConflict(opts ...sql.ConflictOption) *QuestUpsertOne {
	_c.conflict = opts
	return &QuestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuestCreate) OnConflictColumns(columns ...string) *QuestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuestUpsertOne{
		create: _c,
	}
}

type (
	// QuestUpsertOne is the builder for "upsert"-ing
	//  one Quest node.
	QuestUpsertOne struct {
		create *QuestCreate
	}

	// QuestUpsert is the "OnConflict" setter.
	QuestUpsert struct {
		*sql.UpdateSet
	}
)

// SetCharacterID sets the "character_id" field.
func (u *QuestUpsert) SetCharacterID(v int64) *QuestUpsert {
	u.Set(quest.FieldCharacterID, v)
	return u
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *QuestUpsert) UpdateCharacterID() *QuestUpsert {
	u.SetExcluded(quest.FieldCharacterID)
	return u
}

// SetName sets the "name" field.
func (u *QuestUpsert) SetName(v string) *QuestUpsert {
	u.Set(quest.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuestUpsert) UpdateName() *QuestUpsert {
	u.SetExcluded(quest.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *QuestUpsert) SetDescription(v string) *QuestUpsert {
	u.Set(quest.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *QuestUpsert) UpdateDescription() *QuestUpsert {
	u.SetExcluded(quest.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *QuestUpsert) SetStatus(v string) *QuestUpsert {
	u.Set(quest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuestUpsert) UpdateStatus() *QuestUpsert {
	u.SetExcluded(quest.FieldStatus)
	return u
}

// SetObjectives sets the "objectives" field.
func (u *QuestUpsert) SetObjectives(v string) *QuestUpsert {
	u.Set(quest.FieldObjectives, v)
	return u
}

// UpdateObjectives sets the "objectives" field to the value that was provided on create.
func (u *QuestUpsert) UpdateObjectives() *QuestUpsert {
	u.SetExcluded(quest.FieldObjectives)
	return u
}

// SetRewards sets the "rewards" field.
func (u *QuestUpsert) SetRewards(v string) *QuestUpsert {
	u.Set(quest.FieldRewards, v)
	return u
}

// UpdateRewards sets the "rewards" field to the value that was provided on create.
func (u *QuestUpsert) UpdateRewards() *QuestUpsert {
	u.SetExcluded(quest.FieldRewards)
	return u
}

// SetNotes sets the "notes" field.
func (u *QuestUpsert) SetNotes(v string) *QuestUpsert {
	u.Set(quest.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *QuestUpsert) UpdateNotes() *QuestUpsert {
	u.SetExcluded(quest.FieldNotes)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *QuestUpsert) SetCreatedAt(v string) *QuestUpsert {
	u.Set(quest.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QuestUpsert) UpdateCreatedAt() *QuestUpsert {
	u.SetExcluded(quest.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuestUpsert) SetUpdatedAt(v string) *QuestUpsert {
	u.Set(quest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuestUpsert) UpdateUpdatedAt() *QuestUpsert {
	u.SetExcluded(quest.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuestUpsertOne) UpdateNewValues() *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(quest.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Quest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuestUpsertOne) Ignore() *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuestUpsertOne) DoNothing() *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuestCreate.OnConflict
// documentation for more info.
func (u *QuestUpsertOne) Update(set func(*QuestUpsert)) *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuestUpsert{UpdateSet: update})
	}))
	return u
}

// SetCharacterID sets the "character_id" field.
func (u *QuestUpsertOne) SetCharacterID(v int64) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateCharacterID() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateCharacterID()
	})
}

// SetName sets the "name" field.
func (u *QuestUpsertOne) SetName(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateName() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *QuestUpsertOne) SetDescription(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateDescription() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *QuestUpsertOne) SetStatus(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateStatus() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateStatus()
	})
}

// SetObjectives sets the "objectives" field.
func (u *QuestUpsertOne) SetObjectives(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetObjectives(v)
	})
}

// UpdateObjectives sets the "objectives" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateObjectives() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateObjectives()
	})
}

// SetRewards sets the "rewards" field.
func (u *QuestUpsertOne) SetRewards(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetRewards(v)
	})
}

// UpdateRewards sets the "rewards" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateRewards() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateRewards()
	})
}

// SetNotes sets the "notes" field.
func (u *QuestUpsertOne) SetNotes(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateNotes() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateNotes()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *QuestUpsertOne) SetCreatedAt(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateCreatedAt() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuestUpsertOne) SetUpdatedAt(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateUpdatedAt() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *QuestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuestUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuestUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuestCreateBulk is the builder for creating many Quest entities in bulk.
type QuestCreateBulk struct {
	config
	err      error
	builders []*QuestCreate
	conflict []sql.ConflictOption
}

// Save creates the Quest entities in the database.
func (_c *QuestCreateBulk) Save(ctx context.Context) ([]*Quest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Quest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuestCreateBulk) SaveX(ctx context.Context) []*Quest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Quest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuestUpsert) {
//			SetCharacterID(v+v).
//		}).
//		Exec(ctx)
func (_c *QuestCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuestUpsertBulk {
	_c.conflict = opts
	return &QuestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuestCreateBulk) OnConflictColumns(columns ...string) *QuestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuestUpsertBulk{
		create: _c,
	}
}

// QuestUpsertBulk is the builder for "upsert"-ing
// a bulk of Quest nodes.
type QuestUpsertBulk struct {
	create *QuestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuestUpsertBulk) UpdateNewValues() *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(quest.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuestUpsertBulk) Ignore() *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuestUpsertBulk) DoNothing() *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuestCreateBulk.OnConflict
// documentation for more info.
func (u *QuestUpsertBulk) Update(set func(*QuestUpsert)) *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuestUpsert{UpdateSet: update})
	}))
	return u
}

// SetCharacterID sets the "character_id" field.
func (u *QuestUpsertBulk) SetCharacterID(v int64) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateCharacterID() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateCharacterID()
	})
}

// SetName sets the "name" field.
func (u *QuestUpsertBulk) SetName(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateName() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *QuestUpsertBulk) SetDescription(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateDescription() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateDescription()
	})
}

// SetStatus sets the "status" field.
func (u *QuestUpsertBulk) SetStatus(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateStatus() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateStatus()
	})
}

// SetObjectives sets the "objectives" field.
func (u *QuestUpsertBulk) SetObjectives(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetObjectives(v)
	})
}

// UpdateObjectives sets the "objectives" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateObjectives() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateObjectives()
	})
}

// SetRewards sets the "rewards" field.
func (u *QuestUpsertBulk) SetRewards(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetRewards(v)
	})
}

// UpdateRewards sets the "rewards" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateRewards() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateRewards()
	})
}

// SetNotes sets the "notes" field.
func (u *QuestUpsertBulk) SetNotes(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateNotes() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateNotes()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *QuestUpsertBulk) SetCreatedAt(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateCreatedAt() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QuestUpsertBulk) SetUpdatedAt(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateUpdatedAt() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *QuestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
