// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"villum/ent/shop"
	"villum/ent/shoptransaction"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopTransactionCreate is the builder for creating a ShopTransaction entity.
type ShopTransactionCreate struct {
	config
	mutation *ShopTransactionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetShopID sets the "shop_id" field.
func (_c *ShopTransactionCreate) SetShopID(v int64) *ShopTransactionCreate {
	_c.mutation.SetShopID(v)
	return _c
}

// SetCharacterID sets the "character_id" field.
func (_c *ShopTransactionCreate) SetCharacterID(v int64) *ShopTransactionCreate {
	_c.mutation.SetCharacterID(v)
	return _c
}

// SetItemName sets the "item_name" field.
func (_c *ShopTransactionCreate) SetItemName(v string) *ShopTransactionCreate {
	_c.mutation.SetItemName(v)
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *ShopTransactionCreate) SetQuantity(v int) *ShopTransactionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *ShopTransactionCreate) SetNillableQuantity(v *int) *ShopTransactionCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetPriceGp sets the "price_gp" field.
func (_c *ShopTransactionCreate) SetPriceGp(v float64) *ShopTransactionCreate {
	_c.mutation.SetPriceGp(v)
	return _c
}

// SetNillablePriceGp sets the "price_gp" field if the given value is not nil.
func (_c *ShopTransactionCreate) SetNillablePriceGp(v *float64) *ShopTransactionCreate {
	if v != nil {
		_c.SetPriceGp(*v)
	}
	return _c
}

// SetTransactionType sets the "transaction_type" field.
func (_c *ShopTransactionCreate) SetTransactionType(v string) *ShopTransactionCreate {
	_c.mutation.SetTransactionType(v)
	return _c
}

// SetTimestamp sets the "timestamp" field.
func (_c *ShopTransactionCreate) SetTimestamp(v string) *ShopTransactionCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_c *ShopTransactionCreate) SetNillableTimestamp(v *string) *ShopTransactionCreate {
	if v != nil {
		_c.SetTimestamp(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShopTransactionCreate) SetID(v int64) *ShopTransactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetShop sets the "shop" edge to the Shop entity.
func (_c *ShopTransactionCreate) SetShop(v *Shop) *ShopTransactionCreate {
	return _c.SetShopID(v.ID)
}

// Mutation returns the ShopTransactionMutation object of the builder.
func (_c *ShopTransactionCreate) Mutation() *ShopTransactionMutation {
	return _c.mutation
}

// Save creates the ShopTransaction in the database.
func (_c *ShopTransactionCreate) Save(ctx context.Context) (*ShopTransaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShopTransactionCreate) SaveX(ctx context.Context) *ShopTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopTransactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopTransactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShopTransactionCreate) defaults() {
	if _, ok := _c.mutation.Quantity(); !ok {
		v := shoptransaction.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
	if _, ok := _c.mutation.PriceGp(); !ok {
		v := shoptransaction.DefaultPriceGp
		_c.mutation.SetPriceGp(v)
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		v := shoptransaction.DefaultTimestamp
		_c.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShopTransactionCreate) check() error {
	if _, ok := _c.mutation.ShopID(); !ok {
		return &ValidationError{Name: "shop_id", err: errors.New(`ent: missing required field "ShopTransaction.shop_id"`)}
	}
	if _, ok := _c.mutation.CharacterID(); !ok {
		return &ValidationError{Name: "character_id", err: errors.New(`ent: missing required field "ShopTransaction.character_id"`)}
	}
	if _, ok := _c.mutation.ItemName(); !ok {
		return &ValidationError{Name: "item_name", err: errors.New(`ent: missing required field "ShopTransaction.item_name"`)}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "ShopTransaction.quantity"`)}
	}
	if _, ok := _c.mutation.PriceGp(); !ok {
		return &ValidationError{Name: "price_gp", err: errors.New(`ent: missing required field "ShopTransaction.price_gp"`)}
	}
	if _, ok := _c.mutation.TransactionType(); !ok {
		return &ValidationError{Name: "transaction_type", err: errors.New(`ent: missing required field "ShopTransaction.transaction_type"`)}
	}
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "ShopTransaction.timestamp"`)}
	}
	if len(_c.mutation.ShopIDs()) == 0 {
		return &ValidationError{Name: "shop", err: errors.New(`ent: missing required edge "ShopTransaction.shop"`)}
	}
	return nil
}

func (_c *ShopTransactionCreate) sqlSave(ctx context.Context) (*ShopTransaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShopTransactionCreate) createSpec() (*ShopTransaction, *sqlgraph.CreateSpec) {
	var (
		_node = &ShopTransaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shoptransaction.Table, sqlgraph.NewFieldSpec(shoptransaction.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CharacterID(); ok {
		_spec.SetField(shoptransaction.FieldCharacterID, field.TypeInt64, value)
		_node.CharacterID = value
	}
	if value, ok := _c.mutation.ItemName(); ok {
		_spec.SetField(shoptransaction.FieldItemName, field.TypeString, value)
		_node.ItemName = value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(shoptransaction.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.PriceGp(); ok {
		_spec.SetField(shoptransaction.FieldPriceGp, field.TypeFloat64, value)
		_node.PriceGp = value
	}
	if value, ok := _c.mutation.TransactionType(); ok {
		_spec.SetField(shoptransaction.FieldTransactionType, field.TypeString, value)
		_node.TransactionType = value
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(shoptransaction.FieldTimestamp, field.TypeString, value)
		_node.Timestamp = value
	}
	if nodes := _c.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shoptransaction.ShopTable,
			Columns: []string{shoptransaction.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShopID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopTransaction.Create().
//		SetShopID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopTransactionUpsert) {
//			SetShopID(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopTransactionCreate) OnConflict(opts ...sql.ConflictOption) *ShopTransactionUpsertOne {
	_c.conflict = opts
	return &ShopTransactionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopTransactionCreate) OnConflictColumns(columns ...string) *ShopTransactionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopTransactionUpsertOne{
		create: _c,
	}
}

type (
	// ShopTransactionUpsertOne is the builder for "upsert"-ing
	//  one ShopTransaction node.
	ShopTransactionUpsertOne struct {
		create *ShopTransactionCreate
	}

	// ShopTransactionUpsert is the "OnConflict" setter.
	ShopTransactionUpsert struct {
		*sql.UpdateSet
	}
)

// SetShopID sets the "shop_id" field.
func (u *ShopTransactionUpsert) SetShopID(v int64) *ShopTransactionUpsert {
	u.Set(shoptransaction.FieldShopID, v)
	return u
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *ShopTransactionUpsert) UpdateShopID() *ShopTransactionUpsert {
	u.SetExcluded(shoptransaction.FieldShopID)
	return u
}

// SetCharacterID sets the "character_id" field.
func (u *ShopTransactionUpsert) SetCharacterID(v int64) *ShopTransactionUpsert {
	u.Set(shoptransaction.FieldCharacterID, v)
	return u
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *ShopTransactionUpsert) UpdateCharacterID() *ShopTransactionUpsert {
	u.SetExcluded(shoptransaction.FieldCharacterID)
	return u
}

// AddCharacterID adds v to the "character_id" field.
func (u *ShopTransactionUpsert) AddCharacterID(v int64) *ShopTransactionUpsert {
	u.Add(shoptransaction.FieldCharacterID, v)
	return u
}

// SetItemName sets the "item_name" field.
func (u *ShopTransactionUpsert) SetItemName(v string) *ShopTransactionUpsert {
	u.Set(shoptransaction.FieldItemName, v)
	return u
}

// UpdateItemName sets the "item_name" field to the value that was provided on create.
func (u *ShopTransactionUpsert) UpdateItemName() *ShopTransactionUpsert {
	u.SetExcluded(shoptransaction.FieldItemName)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *ShopTransactionUpsert) SetQuantity(v int) *ShopTransactionUpsert {
	u.Set(shoptransaction.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ShopTransactionUpsert) UpdateQuantity() *ShopTransactionUpsert {
	u.SetExcluded(shoptransaction.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *ShopTransactionUpsert) AddQuantity(v int) *ShopTransactionUpsert {
	u.Add(shoptransaction.FieldQuantity, v)
	return u
}

// SetPriceGp sets the "price_gp" field.
func (u *ShopTransactionUpsert) SetPriceGp(v float64) *ShopTransactionUpsert {
	u.Set(shoptransaction.FieldPriceGp, v)
	return u
}

// UpdatePriceGp sets the "price_gp" field to the value that was provided on create.
func (u *ShopTransactionUpsert) UpdatePriceGp() *ShopTransactionUpsert {
	u.SetExcluded(shoptransaction.FieldPriceGp)
	return u
}

// AddPriceGp adds v to the "price_gp" field.
func (u *ShopTransactionUpsert) AddPriceGp(v float64) *ShopTransactionUpsert {
	u.Add(shoptransaction.FieldPriceGp, v)
	return u
}

// SetTransactionType sets the "transaction_type" field.
func (u *ShopTransactionUpsert) SetTransactionType(v string) *ShopTransactionUpsert {
	u.Set(shoptransaction.FieldTransactionType, v)
	return u
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *ShopTransactionUpsert) UpdateTransactionType() *ShopTransactionUpsert {
	u.SetExcluded(shoptransaction.FieldTransactionType)
	return u
}

// SetTimestamp sets the "timestamp" field.
func (u *ShopTransactionUpsert) SetTimestamp(v string) *ShopTransactionUpsert {
	u.Set(shoptransaction.FieldTimestamp, v)
	return u
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *ShopTransactionUpsert) UpdateTimestamp() *ShopTransactionUpsert {
	u.SetExcluded(shoptransaction.FieldTimestamp)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ShopTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(shoptransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShopTransactionUpsertOne) UpdateNewValues() *ShopTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(shoptransaction.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopTransaction.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShopTransactionUpsertOne) Ignore() *ShopTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopTransactionUpsertOne) DoNothing() *ShopTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopTransactionCreate.OnConflict
// documentation for more info.
func (u *ShopTransactionUpsertOne) Update(set func(*ShopTransactionUpsert)) *ShopTransactionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetShopID sets the "shop_id" field.
func (u *ShopTransactionUpsertOne) SetShopID(v int64) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *ShopTransactionUpsertOne) UpdateShopID() *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateShopID()
	})
}

// SetCharacterID sets the "character_id" field.
func (u *ShopTransactionUpsertOne) SetCharacterID(v int64) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetCharacterID(v)
	})
}

// AddCharacterID adds v to the "character_id" field.
func (u *ShopTransactionUpsertOne) AddCharacterID(v int64) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.AddCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *ShopTransactionUpsertOne) UpdateCharacterID() *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateCharacterID()
	})
}

// SetItemName sets the "item_name" field.
func (u *ShopTransactionUpsertOne) SetItemName(v string) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetItemName(v)
	})
}

// UpdateItemName sets the "item_name" field to the value that was provided on create.
func (u *ShopTransactionUpsertOne) UpdateItemName() *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateItemName()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ShopTransactionUpsertOne) SetQuantity(v int) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ShopTransactionUpsertOne) AddQuantity(v int) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ShopTransactionUpsertOne) UpdateQuantity() *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateQuantity()
	})
}

// SetPriceGp sets the "price_gp" field.
func (u *ShopTransactionUpsertOne) SetPriceGp(v float64) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetPriceGp(v)
	})
}

// AddPriceGp adds v to the "price_gp" field.
func (u *ShopTransactionUpsertOne) AddPriceGp(v float64) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.AddPriceGp(v)
	})
}

// UpdatePriceGp sets the "price_gp" field to the value that was provided on create.
func (u *ShopTransactionUpsertOne) UpdatePriceGp() *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdatePriceGp()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *ShopTransactionUpsertOne) SetTransactionType(v string) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *ShopTransactionUpsertOne) UpdateTransactionType() *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateTransactionType()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *ShopTransactionUpsertOne) SetTimestamp(v string) *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *ShopTransactionUpsertOne) UpdateTimestamp() *ShopTransactionUpsertOne {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateTimestamp()
	})
}

// Exec executes the query.
func (u *ShopTransactionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopTransactionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopTransactionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShopTransactionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShopTransactionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShopTransactionCreateBulk is the builder for creating many ShopTransaction entities in bulk.
type ShopTransactionCreateBulk struct {
	config
	err      error
	builders []*ShopTransactionCreate
	conflict []sql.ConflictOption
}

// Save creates the ShopTransaction entities in the database.
func (_c *ShopTransactionCreateBulk) Save(ctx context.Context) ([]*ShopTransaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShopTransaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShopTransactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShopTransactionCreateBulk) SaveX(ctx context.Context) []*ShopTransaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopTransactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopTransactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ShopTransaction.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopTransactionUpsert) {
//			SetShopID(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopTransactionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShopTransactionUpsertBulk {
	_c.conflict = opts
	return &ShopTransactionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ShopTransaction.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopTransactionCreateBulk) OnConflictColumns(columns ...string) *ShopTransactionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopTransactionUpsertBulk{
		create: _c,
	}
}

// ShopTransactionUpsertBulk is the builder for "upsert"-ing
// a bulk of ShopTransaction nodes.
type ShopTransactionUpsertBulk struct {
	create *ShopTransactionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ShopTransaction.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(shoptransaction.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ShopTransactionUpsertBulk) UpdateNewValues() *ShopTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(shoptransaction.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ShopTransaction.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShopTransactionUpsertBulk) Ignore() *ShopTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopTransactionUpsertBulk) DoNothing() *ShopTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopTransactionCreateBulk.OnConflict
// documentation for more info.
func (u *ShopTransactionUpsertBulk) Update(set func(*ShopTransactionUpsert)) *ShopTransactionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopTransactionUpsert{UpdateSet: update})
	}))
	return u
}

// SetShopID sets the "shop_id" field.
func (u *ShopTransactionUpsertBulk) SetShopID(v int64) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *ShopTransactionUpsertBulk) UpdateShopID() *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateShopID()
	})
}

// SetCharacterID sets the "character_id" field.
func (u *ShopTransactionUpsertBulk) SetCharacterID(v int64) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetCharacterID(v)
	})
}

// AddCharacterID adds v to the "character_id" field.
func (u *ShopTransactionUpsertBulk) AddCharacterID(v int64) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.AddCharacterID(v)
	})
}

// UpdateCharacterID sets the "character_id" field to the value that was provided on create.
func (u *ShopTransactionUpsertBulk) UpdateCharacterID() *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateCharacterID()
	})
}

// SetItemName sets the "item_name" field.
func (u *ShopTransactionUpsertBulk) SetItemName(v string) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetItemName(v)
	})
}

// UpdateItemName sets the "item_name" field to the value that was provided on create.
func (u *ShopTransactionUpsertBulk) UpdateItemName() *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateItemName()
	})
}

// SetQuantity sets the "quantity" field.
func (u *ShopTransactionUpsertBulk) SetQuantity(v int) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *ShopTransactionUpsertBulk) AddQuantity(v int) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *ShopTransactionUpsertBulk) UpdateQuantity() *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateQuantity()
	})
}

// SetPriceGp sets the "price_gp" field.
func (u *ShopTransactionUpsertBulk) SetPriceGp(v float64) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetPriceGp(v)
	})
}

// AddPriceGp adds v to the "price_gp" field.
func (u *ShopTransactionUpsertBulk) AddPriceGp(v float64) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.AddPriceGp(v)
	})
}

// UpdatePriceGp sets the "price_gp" field to the value that was provided on create.
func (u *ShopTransactionUpsertBulk) UpdatePriceGp() *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdatePriceGp()
	})
}

// SetTransactionType sets the "transaction_type" field.
func (u *ShopTransactionUpsertBulk) SetTransactionType(v string) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetTransactionType(v)
	})
}

// UpdateTransactionType sets the "transaction_type" field to the value that was provided on create.
func (u *ShopTransactionUpsertBulk) UpdateTransactionType() *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateTransactionType()
	})
}

// SetTimestamp sets the "timestamp" field.
func (u *ShopTransactionUpsertBulk) SetTimestamp(v string) *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.SetTimestamp(v)
	})
}

// UpdateTimestamp sets the "timestamp" field to the value that was provided on create.
func (u *ShopTransactionUpsertBulk) UpdateTimestamp() *ShopTransactionUpsertBulk {
	return u.Update(func(s *ShopTransactionUpsert) {
		s.UpdateTimestamp()
	})
}

// Exec executes the query.
func (u *ShopTransactionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShopTransactionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopTransactionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopTransactionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
