// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"villum/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"password,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt string `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Characters holds the value of the characters edge.
	Characters []*Character `json:"characters,omitempty"`
	// Locations holds the value of the locations edge.
	Locations []*Location `json:"locations,omitempty"`
	// Npcs holds the value of the npcs edge.
	Npcs []*NPC `json:"npcs,omitempty"`
	// Campaigns holds the value of the campaigns edge.
	Campaigns []*Campaign `json:"campaigns,omitempty"`
	// DiceRolls holds the value of the dice_rolls edge.
	DiceRolls []*DiceRoll `json:"dice_rolls,omitempty"`
	// CraftingRecipes holds the value of the crafting_recipes edge.
	CraftingRecipes []*CraftingRecipe `json:"crafting_recipes,omitempty"`
	// Shops holds the value of the shops edge.
	Shops []*Shop `json:"shops,omitempty"`
	// EncounterTemplates holds the value of the encounter_templates edge.
	EncounterTemplates []*EncounterTemplate `json:"encounter_templates,omitempty"`
	// CampaignMembers holds the value of the campaign_members edge.
	CampaignMembers []*CampaignMember `json:"campaign_members,omitempty"`
	// WikiPages holds the value of the wiki_pages edge.
	WikiPages []*CampaignWikiPage `json:"wiki_pages,omitempty"`
	// ShareLinks holds the value of the share_links edge.
	ShareLinks []*ShareLink `json:"share_links,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [11]bool
}

// CharactersOrErr returns the Characters value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CharactersOrErr() ([]*Character, error) {
	if e.loadedTypes[0] {
		return e.Characters, nil
	}
	return nil, &NotLoadedError{edge: "characters"}
}

// LocationsOrErr returns the Locations value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) LocationsOrErr() ([]*Location, error) {
	if e.loadedTypes[1] {
		return e.Locations, nil
	}
	return nil, &NotLoadedError{edge: "locations"}
}

// NpcsOrErr returns the Npcs value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) NpcsOrErr() ([]*NPC, error) {
	if e.loadedTypes[2] {
		return e.Npcs, nil
	}
	return nil, &NotLoadedError{edge: "npcs"}
}

// CampaignsOrErr returns the Campaigns value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CampaignsOrErr() ([]*Campaign, error) {
	if e.loadedTypes[3] {
		return e.Campaigns, nil
	}
	return nil, &NotLoadedError{edge: "campaigns"}
}

// DiceRollsOrErr returns the DiceRolls value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) DiceRollsOrErr() ([]*DiceRoll, error) {
	if e.loadedTypes[4] {
		return e.DiceRolls, nil
	}
	return nil, &NotLoadedError{edge: "dice_rolls"}
}

// CraftingRecipesOrErr returns the CraftingRecipes value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CraftingRecipesOrErr() ([]*CraftingRecipe, error) {
	if e.loadedTypes[5] {
		return e.CraftingRecipes, nil
	}
	return nil, &NotLoadedError{edge: "crafting_recipes"}
}

// ShopsOrErr returns the Shops value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ShopsOrErr() ([]*Shop, error) {
	if e.loadedTypes[6] {
		return e.Shops, nil
	}
	return nil, &NotLoadedError{edge: "shops"}
}

// EncounterTemplatesOrErr returns the EncounterTemplates value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) EncounterTemplatesOrErr() ([]*EncounterTemplate, error) {
	if e.loadedTypes[7] {
		return e.EncounterTemplates, nil
	}
	return nil, &NotLoadedError{edge: "encounter_templates"}
}

// CampaignMembersOrErr returns the CampaignMembers value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CampaignMembersOrErr() ([]*CampaignMember, error) {
	if e.loadedTypes[8] {
		return e.CampaignMembers, nil
	}
	return nil, &NotLoadedError{edge: "campaign_members"}
}

// WikiPagesOrErr returns the WikiPages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) WikiPagesOrErr() ([]*CampaignWikiPage, error) {
	if e.loadedTypes[9] {
		return e.WikiPages, nil
	}
	return nil, &NotLoadedError{edge: "wiki_pages"}
}

// ShareLinksOrErr returns the ShareLinks value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ShareLinksOrErr() ([]*ShareLink, error) {
	if e.loadedTypes[10] {
		return e.ShareLinks, nil
	}
	return nil, &NotLoadedError{edge: "share_links"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldPassword, user.FieldDisplayName, user.FieldRole, user.FieldEmail, user.FieldCreatedAt:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case user.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case user.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCharacters queries the "characters" edge of the User entity.
func (_m *User) QueryCharacters() *CharacterQuery {
	return NewUserClient(_m.config).QueryCharacters(_m)
}

// QueryLocations queries the "locations" edge of the User entity.
func (_m *User) QueryLocations() *LocationQuery {
	return NewUserClient(_m.config).QueryLocations(_m)
}

// QueryNpcs queries the "npcs" edge of the User entity.
func (_m *User) QueryNpcs() *NPCQuery {
	return NewUserClient(_m.config).QueryNpcs(_m)
}

// QueryCampaigns queries the "campaigns" edge of the User entity.
func (_m *User) QueryCampaigns() *CampaignQuery {
	return NewUserClient(_m.config).QueryCampaigns(_m)
}

// QueryDiceRolls queries the "dice_rolls" edge of the User entity.
func (_m *User) QueryDiceRolls() *DiceRollQuery {
	return NewUserClient(_m.config).QueryDiceRolls(_m)
}

// QueryCraftingRecipes queries the "crafting_recipes" edge of the User entity.
func (_m *User) QueryCraftingRecipes() *CraftingRecipeQuery {
	return NewUserClient(_m.config).QueryCraftingRecipes(_m)
}

// QueryShops queries the "shops" edge of the User entity.
func (_m *User) QueryShops() *ShopQuery {
	return NewUserClient(_m.config).QueryShops(_m)
}

// QueryEncounterTemplates queries the "encounter_templates" edge of the User entity.
func (_m *User) QueryEncounterTemplates() *EncounterTemplateQuery {
	return NewUserClient(_m.config).QueryEncounterTemplates(_m)
}

// QueryCampaignMembers queries the "campaign_members" edge of the User entity.
func (_m *User) QueryCampaignMembers() *CampaignMemberQuery {
	return NewUserClient(_m.config).QueryCampaignMembers(_m)
}

// QueryWikiPages queries the "wiki_pages" edge of the User entity.
func (_m *User) QueryWikiPages() *CampaignWikiPageQuery {
	return NewUserClient(_m.config).QueryWikiPages(_m)
}

// QueryShareLinks queries the "share_links" edge of the User entity.
func (_m *User) QueryShareLinks() *ShareLinkQuery {
	return NewUserClient(_m.config).QueryShareLinks(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(_m.Password)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt)
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
