// Code generated by ent, DO NOT EDIT.

package backupsetting

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the backupsetting type in the database.
	Label = "backup_setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldIntervalHours holds the string denoting the interval_hours field in the database.
	FieldIntervalHours = "interval_hours"
	// FieldIntervalDays holds the string denoting the interval_days field in the database.
	FieldIntervalDays = "interval_days"
	// FieldKeepCount holds the string denoting the keep_count field in the database.
	FieldKeepCount = "keep_count"
	// FieldLastBackup holds the string denoting the last_backup field in the database.
	FieldLastBackup = "last_backup"
	// Table holds the table name of the backupsetting in the database.
	Table = "backup_settings"
)

// Columns holds all SQL columns for backupsetting fields.
var Columns = []string{
	FieldID,
	FieldEnabled,
	FieldIntervalHours,
	FieldIntervalDays,
	FieldKeepCount,
	FieldLastBackup,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultIntervalHours holds the default value on creation for the "interval_hours" field.
	DefaultIntervalHours int
	// DefaultIntervalDays holds the default value on creation for the "interval_days" field.
	DefaultIntervalDays int
	// DefaultKeepCount holds the default value on creation for the "keep_count" field.
	DefaultKeepCount int
	// DefaultLastBackup holds the default value on creation for the "last_backup" field.
	DefaultLastBackup string
)

// OrderOption defines the ordering options for the BackupSetting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByIntervalHours orders the results by the interval_hours field.
func ByIntervalHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalHours, opts...).ToFunc()
}

// ByIntervalDays orders the results by the interval_days field.
func ByIntervalDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalDays, opts...).ToFunc()
}

// ByKeepCount orders the results by the keep_count field.
func ByKeepCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeepCount, opts...).ToFunc()
}

// ByLastBackup orders the results by the last_backup field.
func ByLastBackup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastBackup, opts...).ToFunc()
}
