// Code generated by ent, DO NOT EDIT.

package oneshotactnpc

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oneshotactnpc type in the database.
	Label = "one_shot_act_npc"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActID holds the string denoting the act_id field in the database.
	FieldActID = "act_id"
	// FieldNpcID holds the string denoting the npc_id field in the database.
	FieldNpcID = "npc_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldIsInline holds the string denoting the is_inline field in the database.
	FieldIsInline = "is_inline"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the oneshotactnpc in the database.
	Table = "oneshot_act_npcs"
)

// Columns holds all SQL columns for oneshotactnpc fields.
var Columns = []string{
	FieldID,
	FieldActID,
	FieldNpcID,
	FieldName,
	FieldRole,
	FieldNotes,
	FieldIsInline,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultIsInline holds the default value on creation for the "is_inline" field.
	DefaultIsInline bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt string
)

// OrderOption defines the ordering options for the OneShotActNPC queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByActID orders the results by the act_id field.
func ByActID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActID, opts...).ToFunc()
}

// ByNpcID orders the results by the npc_id field.
func ByNpcID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNpcID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByIsInline orders the results by the is_inline field.
func ByIsInline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsInline, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
