name: OTel Export

on:
  workflow_call:

jobs:
  otel:
    permissions:
      contents: read
      actions: read
      pull-requests: read
      checks: read
    name: OpenTelemetry Export Trace
    runs-on: ubuntu-latest
    steps:
      - run: echo "otel"
